// resources/components/homepage/Homepage.vue
<script setup>
  import { computed } from "vue";
  import { useApiStore } from "../../stores/api";
  import AppLink from "../app-link/AppLink.vue";
  import CachedImage from "../cached-image/CachedImage.vue";
  import SocialLinks from "../social-links/SocialLinks.vue";
  import "./homepage.css";

  const apiStore = useApiStore();

  const hasLogin = computed(function hasAvailableLogin() {
    return Boolean(apiStore.client || apiStore.hasStoredCredentials);
  });
</script>

<template>
  <div id="homepage">
    <SocialLinks />
    <div class="logo">
      <CachedImage alt="GIM hub" src="/images/logo-quarter.webp" />
    </div>
    <div id="homepage-links">
      <AppLink href="/create-group">Get started</AppLink>
      <AppLink href="/demo">Demo</AppLink>
      <AppLink href="/changelog">Changelog</AppLink>
      <AppLink :href="hasLogin ? '/group' : '/login'">{{ hasLogin ? "Go to group" : "Login" }}</AppLink>
    </div>
  </div>
</template>

// resources/components/homepage/homepage.tsx
import { AppLink } from "../app-link/app-link";
import { SocialLinks } from "../social-links/social-links";
import { CachedImage } from "../cached-image/cached-image";
import { useContext, useEffect, useState, type ReactElement } from "react";
import { Context as APIContext } from "../../context/api-context.tsx";

import "./homepage.css";

export const Homepage = (): ReactElement => {
  const { logInLive } = useContext(APIContext) ?? {};
  const [hasLogin, setHasLogin] = useState<boolean>();

  useEffect(() => {
    if (!logInLive) return;

    logInLive().then(
      () => setHasLogin(true),
      () => setHasLogin(false),
    );
  }, [logInLive]);

  const groupLink = <AppLink href="/group">Go to group</AppLink>;
  const loginLink = <AppLink href="/login">Login</AppLink>;
  return (
    <div id="homepage">
      <SocialLinks />
      <div className="logo">
        <CachedImage alt="GIM hub" src="/images/logo-quarter.webp" />
      </div>
      <div id="homepage-links">
        <AppLink href="/create-group">Get started</AppLink>
        <AppLink href="/demo">Demo</AppLink>
        <AppLink href="/changelog">Changelog</AppLink>
        {hasLogin ? groupLink : loginLink}
      </div>
    </div>
  );
};
