// resources/components/player-panel/PlayerQuests.vue
<script setup>
  import { computed, ref } from "vue";
  import { useGameDataStore } from "../../stores/game-data";
  import { useMemberQuests } from "../../stores/group";
  import CachedImage from "../cached-image/CachedImage.vue";
  import SearchElement from "../search-element/SearchElement.vue";
  import "./player-quests.css";

  const props = defineProps({
    member: { type: String, required: true },
  });

  const gameDataStore = useGameDataStore();
  const quests = useMemberQuests(function getMember() {
    return props.member;
  });

  const nameFilter = ref("");

  const questList = computed(function getQuestList() {
    return [...(gameDataStore.gameData.quests?.entries() ?? [])]
      .filter(function matchesFilter([, quest]) {
        return !quest.hidden && quest.name.toLowerCase().includes(nameFilter.value.toLowerCase());
      })
      .map(function buildQuest([id, quest]) {
        return { id, ...quest, status: quests.value?.get(id) ?? "NOT_STARTED" };
      });
  });
  const possiblePoints = computed(function getPossiblePoints() {
    return [...(gameDataStore.gameData.quests?.values() ?? [])].reduce(function addPoints(total, quest) {
      return total + quest.points;
    }, 0);
  });
  const currentPoints = computed(function getCurrentPoints() {
    return [...(quests.value?.entries() ?? [])].reduce(function addCompletedPoints(total, [id, progress]) {
      return progress === "FINISHED" ? total + (gameDataStore.gameData.quests?.get(id)?.points ?? 0) : total;
    }, 0);
  });
  const questSections = computed(function getQuestSections() {
    return [
      {
        title: "Free quests",
        quests: questList.value.filter(function isFree(quest) {
          return !quest.member && !quest.tutorial;
        }),
      },
      {
        title: "Members' quests",
        quests: questList.value.filter(function isMembersQuest(quest) {
          return quest.member && !quest.miniquest && !quest.tutorial;
        }),
      },
      {
        title: "Miniquests",
        quests: questList.value.filter(function isMiniquest(quest) {
          return quest.miniquest;
        }),
      },
      {
        title: "Tutorial",
        quests: questList.value.filter(function isTutorial(quest) {
          return quest.tutorial;
        }),
      },
    ];
  });

  function getQuestWikiLink(name) {
    return `https://oldschool.runescape.wiki/w/${name.replaceAll(" ", "_")}/Quick_guide`;
  }

  function getQuestClass(status) {
    return {
      NOT_STARTED: "player-quests-not-started",
      IN_PROGRESS: "player-quests-in-progress",
      FINISHED: "player-quests-finished",
    }[status];
  }

  function getDifficultyIcon(difficulty) {
    return {
      Novice: "/icons/3399-0.png",
      Intermediate: "/icons/3400-0.png",
      Experienced: "/icons/3402-0.png",
      Master: "/icons/3403-0.png",
      Grandmaster: "/icons/3404-0.png",
      Special: "/icons/3404-0.png",
    }[difficulty];
  }
</script>

<template>
  <div class="player-quests">
    <div class="player-quests-top">
      <SearchElement class-name="player-quests-filter" placeholder="Filter quests" @change="nameFilter = $event" />
      <div class="player-quests-points">
        <span class="player-quests-current-points">{{ currentPoints }}</span> / {{ possiblePoints }}
      </div>
    </div>
    <div class="player-quests-list">
      <template v-for="section in questSections" :key="section.title">
        <h4 class="player-quests-section-header">{{ section.title }}</h4>
        <a
          v-for="quest in section.quests"
          :key="quest.id"
          :href="getQuestWikiLink(quest.name)"
          :class="['player-quests-quest', getQuestClass(quest.status)]"
          target="_blank"
          rel="noopener noreferrer"
        >
          <CachedImage
            class="player-quests-difficulty-icon"
            :src="getDifficultyIcon(quest.difficulty)"
            :alt="quest.difficulty"
          />
          {{ quest.name }}
        </a>
      </template>
    </div>
  </div>
</template>

// resources/components/player-panel/player-quests.tsx
import { useContext, useState, type ReactElement } from "react";
import type { QuestDifficulty, QuestStatus } from "../../game/quests";
import { SearchElement } from "../search-element/search-element";
import { GameDataContext } from "../../context/game-data-context";
import type * as Member from "../../game/member";
import { useMemberQuestsContext } from "../../context/group-context";
import { CachedImage } from "../cached-image/cached-image";
import { formatTitle } from "../../ts/format-title";

import "./player-quests.css";

const getQuestWikiLinkURL = (name: string): string => {
  const wikiName = name.replaceAll(" ", "_");
  return `https://oldschool.runescape.wiki/w/${wikiName}/Quick_guide`;
};

const getClassForQuestStatus = (status: QuestStatus): string => {
  switch (status) {
    case "NOT_STARTED":
      return "player-quests-not-started";
    case "IN_PROGRESS":
      return "player-quests-in-progress";
    case "FINISHED":
      return "player-quests-finished";
  }
};

export const PlayerQuests = ({ member }: { member: Member.Name }): ReactElement => {
  const [nameFilter, setNameFilter] = useState<string>("");
  const { quests: questData } = useContext(GameDataContext);
  const quests = useMemberQuestsContext(member);

  const getDifficultyIconURL = (difficulty: QuestDifficulty): string => {
    switch (difficulty) {
      case "Novice":
        return "/icons/3399-0.png";
      case "Intermediate":
        return "/icons/3400-0.png";
      case "Experienced":
        return "/icons/3402-0.png";
      case "Master":
        return "/icons/3403-0.png";
      case "Grandmaster":
        return "/icons/3404-0.png";
      case "Special":
        return "/icons/3404-0.png";
    }
  };

  let possiblePoints = 0;
  questData?.forEach(({ points }) => (possiblePoints += points));
  let currentPoints = 0;
  quests?.forEach((progress, id) => {
    if (progress !== "FINISHED") return;
    currentPoints += questData?.get(id)?.points ?? 0;
  });

  const questList = [
    ...(questData
      ?.entries()
      .filter(([, { name, hidden }]) => !hidden && name.toLowerCase().includes(nameFilter?.toLowerCase()))
      .map(([id, { name, difficulty, member, miniquest, tutorial }]) => {
        const status = quests?.get(id) ?? "NOT_STARTED";
        return {
          member,
          miniquest,
          tutorial,
          element: (
            <a
              key={id}
              href={getQuestWikiLinkURL(name)}
              className={`player-quests-quest ${getClassForQuestStatus(status)}`}
              target="_blank"
              rel="noopener noreferrer"
            >
              <CachedImage
                className="player-quests-difficulty-icon"
                src={getDifficultyIconURL(difficulty)}
                alt={difficulty}
              />
              {name}
            </a>
          ),
        };
      }) ?? []),
  ];

  const tutorialQuests = questList?.filter(({ tutorial }) => !!tutorial).map(({ element }) => element);
  const freeQuests = questList?.filter(({ member, tutorial }) => !member && !tutorial).map(({ element }) => element);
  const membersQuests = questList
    ?.filter(({ member, miniquest, tutorial }) => {
      return member && !miniquest && !tutorial;
    })
    .map(({ element }) => element);
  const miniquestQuests = questList?.filter(({ miniquest }) => !!miniquest).map(({ element }) => element);

  return (
    <div className="player-quests">
      <div className="player-quests-top">
        <SearchElement className="player-quests-filter" onChange={setNameFilter} placeholder="Filter quests" />
        <div className="player-quests-points">
          <span className="player-quests-current-points">{currentPoints}</span> / {possiblePoints}
        </div>
      </div>
      <div className="player-quests-list">
        <h4 className="player-quests-section-header">{formatTitle("Free quests")}</h4>
        {freeQuests}
        <h4 className="player-quests-section-header">{formatTitle("Members' quests")}</h4>
        {membersQuests}
        <h4 className="player-quests-section-header">{formatTitle("Miniquests")}</h4>
        {miniquestQuests}
        <h4 className="player-quests-section-header">{formatTitle("Tutorial")}</h4>
        {tutorialQuests}
      </div>
    </div>
  );
};
