// resources/components/player-panel/PlayerInventory.vue
<script setup>
  import { computed } from "vue";
  import { useGameDataStore } from "../../stores/game-data";
  import { useMemberInventory, useMemberRunePouch } from "../../stores/group";
  import {
    composeItemIconHref,
    formatShortQuantity,
    formatVeryShortQuantity,
    isRunePouch,
    mappedGEPrice,
    mappedHighAlch,
    quantityColor,
  } from "../../game/items";
  import { serializeTooltip } from "../tooltip/tooltip-data";
  import CachedImage from "../cached-image/CachedImage.vue";
  import "./player-inventory.css";

  const props = defineProps({
    member: { type: String, required: true },
  });

  const gameDataStore = useGameDataStore();
  const inventory = useMemberInventory(function getMember() {
    return props.member;
  });
  const runePouch = useMemberRunePouch(function getMember() {
    return props.member;
  });

  const slots = computed(function getInventorySlots() {
    return Array.from({ length: 28 }, function buildSlot(_value, index) {
      const item = inventory.value?.get(index);
      const itemData = item ? gameDataStore.gameData.items?.get(item.itemID) : undefined;

      if (!item || !itemData) {
        return { key: `empty ${index}` };
      }

      const runes = [];
      let tooltipData = {
        type: "item",
        name: itemData.name,
        quantity: item.quantity,
        highAlch: mappedHighAlch(item.itemID, gameDataStore.gameData.items),
        gePrice: mappedGEPrice(item.itemID, gameDataStore.gameData.gePrices, gameDataStore.gameData.items),
      };

      if (isRunePouch(item.itemID) && runePouch.value) {
        let totalHighAlch = 0;
        let totalGePrice = 0;

        for (const [runeId, { quantity }] of runePouch.value) {
          const runeData = gameDataStore.gameData.items?.get(runeId);

          if (!runeData) {
            continue;
          }

          totalGePrice +=
            mappedGEPrice(runeId, gameDataStore.gameData.gePrices, gameDataStore.gameData.items) * quantity;
          totalHighAlch += runeData.highalch * quantity;
          runes.push({
            id: runeId,
            name: runeData.name,
            quantity,
            icon: composeItemIconHref({ itemID: runeId, quantity }, runeData),
          });
        }

        tooltipData = {
          type: "rune-pouch",
          name: itemData.name,
          totalHighAlch,
          totalGePrice,
          runes: runes.map(function getRuneTooltip(rune) {
            return { name: rune.name, quantity: rune.quantity };
          }),
        };
      }

      return {
        key: `${item.itemID} ${item.quantity} ${index} ${runes
          .map(function getRuneKey(rune) {
            return `${rune.id} ${rune.quantity}`;
          })
          .join(" ")}`,
        item,
        icon: composeItemIconHref(item, itemData),
        link: `https://oldschool.runescape.wiki/w/Special:Lookup?type=item&id=${item.itemID}`,
        tooltip: serializeTooltip(tooltipData),
        runes,
      };
    });
  });
</script>

<template>
  <div class="player-inventory">
    <div class="player-inventory-background">
      <template v-for="slot in slots" :key="slot.key">
        <a
          v-if="slot.item"
          :href="slot.link"
          class="player-inventory-item-box"
          target="_blank"
          rel="noopener noreferrer"
          :data-tooltip="slot.tooltip"
        >
          <CachedImage alt="osrs item" :src="slot.icon" />
          <span
            v-if="slot.item.quantity > 1"
            class="player-inventory-item-quantity"
            :style="{ color: quantityColor(slot.item.quantity) }"
          >
            {{ formatShortQuantity(slot.item.quantity) }}
          </span>
          <div
            v-if="slot.runes.length > 0"
            :class="['player-inventory-pouch-container', { 'player-inventory-pouch-vertical': slot.runes.length <= 3 }]"
          >
            <div v-for="rune in slot.runes" :key="rune.id" class="player-inventory-pouch-item-box">
              <CachedImage :alt="rune.name" :src="rune.icon" />
              <span class="player-inventory-item-quantity" :style="{ color: quantityColor(rune.quantity) }">
                {{ formatVeryShortQuantity(rune.quantity) }}
              </span>
            </div>
          </div>
        </a>
        <span v-else />
      </template>
    </div>
  </div>
</template>

// resources/components/player-panel/player-inventory.tsx
import { useContext, type ReactElement, type ReactNode } from "react";
import { GameDataContext } from "../../context/game-data-context";
import * as Member from "../../game/member";
import { useMemberInventoryContext, useMemberRunePouchContext } from "../../context/group-context";
import {
  composeItemIconHref,
  formatShortQuantity,
  formatVeryShortQuantity,
  quantityColor,
  isRunePouch,
  mappedGEPrice,
  mappedHighAlch,
} from "../../game/items";
import { CachedImage } from "../cached-image/cached-image";
import { serializeTooltip, type ItemTooltipData } from "../tooltip/tooltip-data";

import "./player-inventory.css";

interface ItemBoxPouchRuneProps {
  iconSource: string;
  name: string;
  quantity: number;
}
const ItemBoxPouchRune = ({ iconSource, name, quantity }: ItemBoxPouchRuneProps): ReactElement => {
  return (
    <div className="player-inventory-pouch-item-box">
      <CachedImage alt={name} src={iconSource} />
      <span className="player-inventory-item-quantity" style={{ color: quantityColor(quantity) }}>
        {formatVeryShortQuantity(quantity)}
      </span>
    </div>
  );
};

interface ItemBoxProps {
  link: string;
  iconSource: string;
  quantity: number;
  tooltip: string;
  children?: ReactNode;
}
const ItemBox = ({ link, iconSource, quantity, tooltip, children }: ItemBoxProps): ReactElement => {
  let quantityOverlay = undefined;
  if (quantity > 1) {
    quantityOverlay = (
      <span className="player-inventory-item-quantity" style={{ color: quantityColor(quantity) }}>
        {formatShortQuantity(quantity)}
      </span>
    );
  }

  return (
    <a
      href={link}
      className="player-inventory-item-box"
      target="_blank"
      rel="noopener noreferrer"
      data-tooltip={tooltip}
    >
      <CachedImage alt="osrs item" src={iconSource} />
      {quantityOverlay}
      {children}
    </a>
  );
};

export const PlayerInventory = ({ member }: { member: Member.Name }): ReactElement => {
  const { items: itemData, gePrices: geData } = useContext(GameDataContext);
  const items = useMemberInventoryContext(member);
  const runePouch = useMemberRunePouchContext(member);

  const itemElements = [];
  for (let index = 0; index < 28; index++) {
    const item = items?.get(index);
    if (!item || !itemData?.has(item.itemID)) {
      itemElements.push(<span key={`empty ${index}`} />);
      continue;
    }

    const { itemID, quantity } = item;
    const itemDatum = itemData.get(itemID)!;

    const wikiLinkHref = `https://oldschool.runescape.wiki/w/Special:Lookup?type=item&id=${item.itemID}`;
    const iconHref = composeItemIconHref(item, itemDatum);

    let pouchOverlay = undefined;

    let key = `${item.itemID} ${item.quantity} ${index} `;
    let tooltipData: ItemTooltipData = {
      type: "item",
      name: itemDatum.name,
      quantity: quantity,
      highAlch: mappedHighAlch(itemID, itemData),
      gePrice: mappedGEPrice(itemID, geData, itemData),
    };
    if (isRunePouch(itemID) && runePouch) {
      const overlayItemIcons = [];
      let totalHighAlch = 0;
      let totalGePrice = 0;
      const runes: { name: string; quantity: number }[] = [];
      for (const [runeID, { quantity: runeQuantity }] of runePouch) {
        const runeDatum = itemData?.get(runeID);
        if (!runeDatum) continue;

        const runeKey = `${runeID} ${runeQuantity}`;
        key += runeKey;
        totalGePrice += mappedGEPrice(runeID, geData, itemData) * runeQuantity;
        totalHighAlch += runeDatum.highalch * runeQuantity;
        runes.push({ name: runeDatum.name, quantity: runeQuantity });

        const runeIconSource = composeItemIconHref({ itemID: runeID, quantity: runeQuantity }, runeDatum);
        overlayItemIcons.push(
          <ItemBoxPouchRune key={runeKey} iconSource={runeIconSource} name={runeDatum.name} quantity={runeQuantity} />,
        );
      }
      tooltipData = {
        type: "rune-pouch",
        name: itemDatum.name,
        totalHighAlch,
        totalGePrice,
        runes,
      };
      if (overlayItemIcons.length > 0) {
        const containerClass =
          overlayItemIcons.length <= 3
            ? "player-inventory-pouch-container player-inventory-pouch-vertical"
            : "player-inventory-pouch-container";
        pouchOverlay = <div className={containerClass}>{overlayItemIcons}</div>;
      }
    }

    itemElements.push(
      <ItemBox
        key={key}
        quantity={quantity}
        link={wikiLinkHref}
        iconSource={iconHref}
        tooltip={serializeTooltip(tooltipData)}
      >
        {pouchOverlay}
      </ItemBox>,
    );
  }

  return (
    <div className="player-inventory">
      <div className="player-inventory-background">{itemElements}</div>
    </div>
  );
};
