// resources/components/player-panel/player-diaries.tsx
import { useContext, type ReactElement } from "react";
import { StatBar } from "./stat-bar";
import { DiaryRegion, DiaryTier } from "../../game/diaries";
import { useModal } from "../modal/modal";
import { computeVirtualLevelFromXP, type Level } from "../../game/skill";
import { GameDataContext } from "../../context/game-data-context";
import type * as Member from "../../game/member";
import { useMemberDiariesContext, useMemberQuestsContext, useMemberSkillsContext } from "../../context/group-context";
import { DiaryRegionWindow, type DiaryTaskProgress } from "../achievement-diary/achievement-diary";

import "./player-diaries.css";

interface DiarySummaryProps {
  region: DiaryRegion;
  onClick: (region: DiaryRegion) => void;
  completionRatioRegion: { completed: number; total: number };
  completionRatioPerTier: number[];
}

const DiarySummary = ({
  region,
  onClick,
  completionRatioRegion,
  completionRatioPerTier,
}: DiarySummaryProps): ReactElement => {
  return (
    <>
      <button className={`rsborder-tiny diary-completion`} onClick={() => onClick(region)}>
        <div className="diary-completion-top">
          <span>{region}</span>
          <span>
            {completionRatioRegion.completed}/{completionRatioRegion.total}
          </span>
        </div>
        <div className="diary-completion-bottom">
          {completionRatioPerTier.map((ratio, index) => {
            /*
             * With CSS's HSL color model, 0-107 is a gradient from red, orange,
             * yellow, then green. So we can multiply the hue to get the effect
             * of more complete diaries becoming redder, assuming ratio is
             * between 0 and 1.
             */
            const hue = 107 * ratio;
            return (
              <StatBar
                key={`${ratio}-${index}`}
                color={`hsl(${hue}, 100%, 41%)`}
                bgColor="rgba(0, 0, 0, 0.5)"
                ratio={ratio}
              />
            );
          })}
        </div>
      </button>
    </>
  );
};

export const PlayerDiaries = ({ member }: { member: Member.Name }): ReactElement => {
  const { quests: questData, diaries: diaryData } = useContext(GameDataContext);
  const skills = useMemberSkillsContext(member);
  const diaries = useMemberDiariesContext(member);
  const quests = useMemberQuestsContext(member);

  const { open: openModal, modal } = useModal(DiaryRegionWindow);

  if (diaryData === undefined) return <></>;

  const summaryElements = [];
  for (const [region, tasksByTier] of diaryData) {
    const completionByTier = diaries?.[region];

    const detailedCompletionAllTiers: [DiaryTier, DiaryTaskProgress[]][] = [];
    const completionRatioForRegion = {
      completed: 0,
      total: 0,
    };
    const completionRatioPerTier: number[] = [];
    tasksByTier.forEach((tasks, tier) => {
      const completionPerTask = completionByTier?.[tier];
      const detailedCompletionForTier: DiaryTaskProgress[] = [];
      let completedTasksForTier = 0;
      let totalTasksForTier = 0;
      for (const [index, task] of tasks.entries()) {
        totalTasksForTier += 1;

        const completed = !!completionPerTask?.[index];
        if (completed) completedTasksForTier += 1;

        detailedCompletionForTier.push({
          complete: completed,
          description: task.task,
          quests: task.requirements.quests.map((id) => ({
            name: questData?.get(id)?.name ?? "Summer's End",
            complete: quests?.get(id) === "FINISHED",
          })),
          skills: task.requirements.skills.map(({ skill, level }) => ({
            skill,
            required: level as Level,
            current: computeVirtualLevelFromXP(skills?.[skill] ?? 0),
          })),
        });
      }

      completionRatioPerTier.push(completedTasksForTier / totalTasksForTier);
      completionRatioForRegion.completed += completedTasksForTier;
      completionRatioForRegion.total += totalTasksForTier;

      detailedCompletionAllTiers.push([tier, detailedCompletionForTier]);
    });

    summaryElements.push(
      <DiarySummary
        key={region}
        region={region}
        onClick={(region) => openModal({ region, player: member, progress: detailedCompletionAllTiers })}
        completionRatioRegion={completionRatioForRegion}
        completionRatioPerTier={completionRatioPerTier}
      />,
    );
  }

  return (
    <div className="player-diaries">
      <h2 className="player-diaries-title">Achievement diaries</h2>
      <div className="player-diaries-completions">{summaryElements}</div>
      {modal}
    </div>
  );
};

// resources/components/player-panel/PlayerDiaries.vue
<script setup>
  import { computed } from "vue";
  import { useGameDataStore } from "../../stores/game-data";
  import { useMemberDiaries, useMemberQuests, useMemberSkills } from "../../stores/group";
  import { computeVirtualLevelFromXP } from "../../game/skill";
  import DiaryRegionWindow from "../achievement-diary/DiaryRegionWindow.vue";
  import Modal from "../modal/Modal.vue";
  import { useModal } from "../modal/use-modal";
  import StatBar from "./StatBar.vue";
  import "./player-diaries.css";

  const props = defineProps({
    member: { type: String, required: true },
  });

  const gameDataStore = useGameDataStore();
  const skills = useMemberSkills(function getMember() {
    return props.member;
  });
  const diaries = useMemberDiaries(function getMember() {
    return props.member;
  });
  const quests = useMemberQuests(function getMember() {
    return props.member;
  });

  const { open: modalOpen, componentProps: modalProps, openModal, closeModal } = useModal();

  const summaries = computed(function getDiarySummaries() {
    const diaryData = gameDataStore.gameData.diaries;

    if (!diaryData) {
      return [];
    }

    return [...diaryData].map(function buildRegionSummary([region, tasksByTier]) {
      const detailedProgress = [];
      const completion = { completed: 0, total: 0 };
      const completionPerTier = [];

      tasksByTier.forEach(function buildTier(tasks, tier) {
        const detailedTasks = [];
        let completedTasks = 0;

        for (const [index, task] of tasks.entries()) {
          const complete = Boolean(diaries.value?.[region]?.[tier]?.[index]);
          completedTasks += complete ? 1 : 0;
          detailedTasks.push({
            complete,
            description: task.task,
            quests: task.requirements.quests.map(function buildQuest(id) {
              return {
                name: gameDataStore.gameData.quests?.get(id)?.name ?? "Summer's End",
                complete: quests.value?.get(id) === "FINISHED",
              };
            }),
            skills: task.requirements.skills.map(function buildSkill({ skill, level }) {
              return { skill, required: level, current: computeVirtualLevelFromXP(skills.value?.[skill] ?? 0) };
            }),
          });
        }

        completionPerTier.push(completedTasks / tasks.length);
        completion.completed += completedTasks;
        completion.total += tasks.length;
        detailedProgress.push([tier, detailedTasks]);
      });

      return { region, completion, completionPerTier, detailedProgress };
    });
  });

  function openDiary(summary) {
    openModal({ region: summary.region, player: props.member, progress: summary.detailedProgress });
  }
</script>

<template>
  <div class="player-diaries">
    <h2 class="player-diaries-title">Achievement diaries</h2>
    <div class="player-diaries-completions">
      <button
        v-for="summary in summaries"
        :key="summary.region"
        class="rsborder-tiny diary-completion"
        @click="openDiary(summary)"
      >
        <div class="diary-completion-top">
          <span>{{ summary.region }}</span>
          <span>{{ summary.completion.completed }}/{{ summary.completion.total }}</span>
        </div>
        <div class="diary-completion-bottom">
          <StatBar
            v-for="(ratio, index) in summary.completionPerTier"
            :key="`${ratio}-${index}`"
            :color="`hsl(${107 * ratio}, 100%, 41%)`"
            bg-color="rgba(0, 0, 0, 0.5)"
            :ratio="ratio"
          />
        </div>
      </button>
    </div>

    <Modal :open="modalOpen" :component="DiaryRegionWindow" :component-props="modalProps" @close="closeModal" />
  </div>
</template>
