// resources/components/app/app.tsx
import { Routes, Route, Navigate, useLocation } from "react-router-dom";
import { type ReactElement } from "react";
import { UnauthedLayout, AuthedLayout } from "../layout/layout";
import { Homepage } from "../homepage/homepage";
import { SetupInstructions } from "../setup-instructions/setup-instructions";
import { LoginPage } from "../login-page/login-page";
import { LogoutPage } from "../logout-page/logout-page";
import { CanvasMap } from "../canvas-map/canvas-map";
import { ItemsPage } from "../items-page/items-page";
import { Tooltip } from "../tooltip/tooltip";
import { PanelsPage } from "../panels-page/panels-page";
import { SkillGraph } from "../skill-graph/skill-graph";
import { CreateGroupPage } from "../create-group-page/create-group-page";
import { SettingsPage } from "../settings/settings";
import { DemoPage } from "../demo-page/demo-page";

import "./app.css";

export const App = (): ReactElement => {
  const location = useLocation();

  return (
    <>
      <CanvasMap interactive={location.pathname === "/group/map"} />
      <Routes>
        <Route
          index
          element={
            <UnauthedLayout>
              <Homepage />
            </UnauthedLayout>
          }
        />
        <Route path="/demo" element={<DemoPage />} />
        <Route
          path="/create-group"
          element={
            <UnauthedLayout>
              <CreateGroupPage />
            </UnauthedLayout>
          }
        />
        <Route
          path="/login"
          element={
            <UnauthedLayout>
              <LoginPage />
            </UnauthedLayout>
          }
        />
        <Route path="/logout" element={<LogoutPage />} />
        <Route path="/group">
          <Route index element={<Navigate to="items" replace />} />
          <Route
            path="setup-instructions"
            element={
              <AuthedLayout showPanels={false} hideHeader>
                <SetupInstructions />
              </AuthedLayout>
            }
          />
          <Route
            path="items"
            element={
              <AuthedLayout showPanels={true}>
                <ItemsPage />
              </AuthedLayout>
            }
          />
          <Route path="map" element={<AuthedLayout showPanels={true} />} />
          <Route
            path="graphs"
            element={
              <AuthedLayout showPanels={true}>
                <SkillGraph />
              </AuthedLayout>
            }
          />
          <Route
            path="panels"
            element={
              <AuthedLayout showPanels={false}>
                <PanelsPage />
              </AuthedLayout>
            }
          />
          <Route
            path="settings"
            element={
              <AuthedLayout showPanels={true}>
                <SettingsPage />
              </AuthedLayout>
            }
          />
        </Route>
        <Route path="*" element={<Navigate to="/" replace />} />
      </Routes>
      <Tooltip />
    </>
  );
};

// resources/components/app/App.vue
<script setup>
  import { computed, defineAsyncComponent, watch } from "vue";
  import { useRoute } from "vue-router";
  import { applySiteTheme } from "../../game/theme";
  import { useSettingsStore } from "../../stores/settings";
  import AuthedLayout from "../layout/AuthedLayout.vue";
  import UnauthedLayout from "../layout/UnauthedLayout.vue";
  import Tooltip from "../tooltip/Tooltip.vue";
  import "./app.css";

  const CanvasMap = defineAsyncComponent(function loadCanvasMap() {
    return import("../canvas-map/CanvasMap.vue");
  });

  const route = useRoute();
  const settingsStore = useSettingsStore();

  const canvasMapIsInteractive = computed(function canvasMapIsInteractive() {
    return route.path === "/group/map";
  });

  watch(
    [
      function getLayout() {
        return route.meta.layout;
      },
      function getSiteTheme() {
        return settingsStore.siteTheme;
      },
    ],
    function updateTheme([layout, siteTheme]) {
      if (layout === "authed") {
        applySiteTheme(siteTheme);
      }
    },
    { immediate: true },
  );
</script>

<template>
  <CanvasMap :interactive="canvasMapIsInteractive" />

  <RouterView v-slot="{ Component }">
    <AuthedLayout
      v-if="route.meta.layout === 'authed'"
      :show-panels="route.meta.showPanels"
      :hide-header="route.meta.hideHeader"
    >
      <component :is="Component" />
    </AuthedLayout>

    <UnauthedLayout v-else-if="route.meta.layout === 'unauthed'">
      <component :is="Component" />
    </UnauthedLayout>

    <component :is="Component" v-else />
  </RouterView>

  <Tooltip />
</template>
