// resources/components/app-link/AppLink.vue
<script setup>
  import { RouterLink } from "vue-router";
  import "./app-link.css";

  const props = defineProps({
    href: { type: String, required: true },
    selected: { type: Boolean, default: false },
    className: { type: String, default: "" },
  });
</script>

<template>
  <RouterLink :class="['app-link', 'men-button', { active: props.selected }, props.className]" :to="props.href">
    <slot />
  </RouterLink>
</template>

// resources/components/app-link/app-link.tsx
import type { ReactElement, ReactNode } from "react";
import { Link as RouterLink } from "react-router";

import "./app-link.css";

export interface AppLinkProps {
  children: ReactNode;
  href: string;
  selected?: boolean;
  className?: string;
}

export const AppLink = (props: AppLinkProps): ReactElement => {
  return (
    <RouterLink
      className={`app-link men-button ${props.selected ? "active" : ""} ${props.className ?? ""}`}
      to={props.href}
    >
      {props.children}
    </RouterLink>
  );
};
