// resources/components/panels-page/PanelsPage.vue
<script setup>
  import { computed } from "vue";
  import { useGroupStore } from "../../stores/group";
  import PlayerPanel from "../player-panel/PlayerPanel.vue";
  import "./panels-page.css";

  const groupStore = useGroupStore();

  const groupMembers = computed(function getGroupMembers() {
    return [...groupStore.memberNames].filter(function excludeSharedMember(member) {
      return member !== "@SHARED";
    });
  });
</script>

<template>
  <div id="panels-page-container">
    <PlayerPanel v-for="member in groupMembers" :key="member" :member="member" />
  </div>
</template>

// resources/components/panels-page/panels-page.tsx
import { useContext, type ReactElement } from "react";
import { PlayerPanel } from "../player-panel/player-panel";
import { GroupMemberNamesContext } from "../../context/group-context";

import "./panels-page.css";

export const PanelsPage = (): ReactElement => {
  const groupMembers = useContext(GroupMemberNamesContext);

  const panels = groupMembers
    .values()
    .filter((member) => member !== "@SHARED")
    .toArray()
    .map<ReactElement>((member) => <PlayerPanel key={member} member={member} />);

  return <div id="panels-page-container">{panels}</div>;
};
