// resources/components/search-element/search-element.tsx
import type { ReactElement } from "react";

import "./search-element.css";

export const SearchElement = ({
  id,
  className,
  defaultValue,
  placeholder,
  onChange,
}: {
  id?: string;
  className?: string;
  defaultValue?: string;
  placeholder: string;
  onChange: (value: string) => void;
}): ReactElement => {
  return (
    <div id={id}>
      <input
        className={`search-element-input ${className}`}
        placeholder={`${placeholder}`}
        type="text"
        tabIndex={0}
        onChange={(e) => onChange(e.target.value)}
        defaultValue={defaultValue}
      />
    </div>
  );
};

// resources/components/search-element/SearchElement.vue
<script setup>
  import "./search-element.css";

  const props = defineProps({
    id: { type: String, default: undefined },
    className: { type: String, default: "" },
    defaultValue: { type: String, default: undefined },
    value: { type: String, default: undefined },
    placeholder: { type: String, required: true },
  });
  const emit = defineEmits(["change"]);

  function change(event) {
    emit("change", event.target.value);
  }
</script>

<template>
  <div :id="props.id">
    <input
      :class="['search-element-input', props.className]"
      :placeholder="props.placeholder"
      type="text"
      tabindex="0"
      :value="props.value ?? props.defaultValue"
      @input="change"
    />
  </div>
</template>
