// resources/components/create-group-page/CreateGroupPage.vue
<script setup>
  import { computed, ref } from "vue";
  import { useRouter } from "vue-router";
  import * as z from "zod/v4";
  import { fetchCreateGroup } from "../../api/requests/create-group";
  import { useApiStore } from "../../stores/api";
  import { memberNameSchema } from "../../game/member-name";
  import LoadingScreen from "../loading-screen/LoadingScreen.vue";
  import "./create-group-page.css";

  const groupNameSchema = z
    .string("Group name is required.")
    .refine(
      function hasNoOuterSpaces(name) {
        return name === name.trim();
      },
      { error: "Group name cannot begin or end with spaces." },
    )
    .refine(
      function hasAllowedCharacters(name) {
        return !/[^A-Za-z 0-9-_]/g.test(name);
      },
      { error: "Group name must use characters 'A-Z', 'a-z', '0-9', and '-', '_', or ' '." },
    )
    .refine(
      function hasValidLength(name) {
        return name.length >= 1 && name.length <= 16;
      },
      {
        error({ input }) {
          return input.length === 0 ? "Group name is required." : "Group name must be between 1 and 16 characters.";
        },
      },
    )
    .transform(function trimGroupName(name) {
      return name.trim();
    });
  const memberCountSchema = z.coerce
    .number()
    .int()
    .min(2, "Group size must be between 2 and 5.")
    .max(5, "Group size must be between 2 and 5.");
  const memberNamesSchema = z.array(memberNameSchema).nonempty();

  const apiStore = useApiStore();
  const router = useRouter();

  const memberCount = ref();
  const pending = ref(false);
  const formState = ref({ type: "Pending" });

  const groupNameErrors = computed(function getGroupNameErrors() {
    return formState.value.type === "Pending" ? formState.value.groupNameErrors : undefined;
  });
  const memberCountErrors = computed(function getMemberCountErrors() {
    return formState.value.type === "Pending" ? formState.value.memberCountErrors : undefined;
  });
  const memberInputIndexes = computed(function getMemberInputIndexes() {
    return Array.from({ length: memberCount.value ?? 0 }, function getIndex(_value, index) {
      return index;
    });
  });

  async function createGroup(formData) {
    const groupName = groupNameSchema.safeParse(formData.get("group-name"));
    const memberCount = memberCountSchema.safeParse(formData.get("group-member-count"));
    const memberNamesRaw = formData.getAll("member-name");
    const memberNames = memberNamesSchema.safeParse(memberNamesRaw);

    if (!groupName.success || !memberCount.success || !memberNames.success) {
      const memberNameErrors = memberNames.success ? undefined : z.treeifyError(memberNames.error).items;

      return {
        type: "Pending",
        groupNameErrors: groupName.success ? undefined : z.flattenError(groupName.error).formErrors,
        memberCountErrors: memberCount.success ? undefined : z.flattenError(memberCount.error).formErrors,
        memberErrors: memberNames.success
          ? undefined
          : Array.from({ length: memberNamesRaw.length }, function getMemberErrors(_value, index) {
              return memberNameErrors?.at(index)?.errors ?? [];
            }),
      };
    }

    try {
      const credentials = await fetchCreateGroup(groupName.data, memberNames.data);
      await new Promise(function waitForLoadingState(resolve) {
        setTimeout(resolve, 500);
      });

      return { type: "Success", credentials };
    } catch (reason) {
      return { type: "Pending", serverErrors: [reason instanceof Error ? reason.message : "Unknown error"] };
    }
  }

  async function submit(event) {
    pending.value = true;

    if (formState.value.type === "Pending") {
      formState.value = { ...formState.value, serverErrors: undefined };
    }

    try {
      const result = await createGroup(new FormData(event.currentTarget));
      formState.value = result;

      if (result.type === "Success") {
        await apiStore.logInLive(result.credentials);
        await router.push("/group/setup-instructions");
      }
    } catch (reason) {
      console.error("Unexpected error during form submission:", reason);
    } finally {
      pending.value = false;
    }
  }

  function updateMemberCount(event) {
    const newMemberCount = parseInt(event.target.value);

    if (!Number.isSafeInteger(newMemberCount) || newMemberCount === memberCount.value) {
      return;
    }

    if (formState.value.type === "Pending") {
      formState.value = {
        ...formState.value,
        memberErrors: formState.value.memberErrors?.slice(0, Math.min(memberCount.value ?? 0, newMemberCount)),
      };
    }

    memberCount.value = newMemberCount;
  }

  function getMemberErrors(index) {
    return formState.value.type === "Pending" ? formState.value.memberErrors?.at(index) : undefined;
  }
</script>

<template>
  <div id="create-group-container">
    <form id="create-group-window" class="rsborder rsbackground" @submit.prevent="submit">
      <div>
        <h3>Pick a name for your group</h3>
        <p>This does <span class="emphasize">not</span> need to be the in-game name.</p>
        <label for="create-group-group-name">Group name</label>
        <br />
        <input
          id="create-group-group-name"
          name="group-name"
          :class="groupNameErrors?.length ? 'invalid' : 'valid'"
          placeholder="Group name"
          maxlength="16"
        />
        <div class="validation-error">
          <template v-for="(error, index) in groupNameErrors" :key="error">
            <br v-if="index > 0" />
            {{ error }}
          </template>
        </div>
      </div>

      <div>
        <h3>What size is the group?</h3>
        <p>This can be changed later.</p>
        <label for="group-member-count">Group size</label>
        <br />
        <div
          :class="[
            'select-container',
            'rsborder-tiny',
            'rsbackground',
            memberCountErrors?.length ? 'invalid' : 'valid',
          ]"
        >
          <select id="group-member-count" name="group-member-count" value="0" @change="updateMemberCount">
            <option value="0" disabled>Select an option</option>
            <option v-for="count in [2, 3, 4, 5]" :key="count" :value="count">{{ count }} Members</option>
          </select>
        </div>
        <div class="validation-error">
          <template v-for="(error, index) in memberCountErrors" :key="error">
            <br v-if="index > 0" />
            {{ error }}
          </template>
        </div>
      </div>

      <div v-if="memberInputIndexes.length > 0">
        <h3>Enter each members' name</h3>
        <p>This <span class="emphasize">does</span> need to match the in-game name. (Can be changed later)</p>

        <template v-for="index in memberInputIndexes" :key="index">
          <label :for="`create-group-member-name-${index}`">Name for Member {{ index + 1 }}</label>
          <br />
          <input
            aria-required="true"
            :id="`create-group-member-name-${index}`"
            :class="getMemberErrors(index)?.length ? 'invalid' : 'valid'"
            placeholder="Member name"
            name="member-name"
            maxlength="16"
          />
          <div class="validation-error">
            <template v-for="(error, errorIndex) in getMemberErrors(index)" :key="error">
              <br v-if="errorIndex > 0" />
              {{ error }}
            </template>
          </div>
        </template>
      </div>

      <button :disabled="pending" class="men-button" type="submit">Create group</button>

      <div v-if="formState.type === 'Pending' && formState.serverErrors?.length" class="validation-error">
        <template v-for="(error, index) in formState.serverErrors" :key="error">
          <br v-if="index > 0" />
          {{ error }}
        </template>
      </div>

      <div v-if="pending" id="create-group-loading-overlay">
        <LoadingScreen />
      </div>
    </form>
  </div>
</template>

// resources/components/create-group-page/create-group-page.tsx
import {
  Fragment,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type ReactElement,
  type ReactNode,
} from "react";
import Api from "../../api/api";
import { Context as APIContext } from "../../context/api-context";
import { useNavigate } from "react-router-dom";
import * as Member from "../../game/member";
import type { GroupCredentials } from "../../api/credentials";
import * as z from "zod/v4";

import "./create-group-page.css";
import { LoadingScreen } from "../loading-screen/loading-screen";

/**
 * This page is where users can submit initial name and members for a group.
 */

const GroupNameSchema = z
  .string("Group name is required.")
  .refine((name) => name === name.trim(), { error: "Group name cannot begin or end with spaces." })
  .refine((name) => !/[^A-Za-z 0-9-_]/g.test(name), {
    error: "Group name must use characters 'A-Z', 'a-z', '0-9', and '-', '_', or ' '.",
  })
  .refine((name) => name.length >= 1 && name.length <= 16, {
    error: ({ input }) => {
      if ((input as string).length === 0) return "Group name is required.";
      return "Group name must be between 1 and 16 characters.";
    },
  })
  .transform((name) => name.trim());

export const MemberNameSchema = z
  .string("Member name is required.")
  .refine((name) => name === name.trim(), { error: "Member name cannot begin or end with spaces." })
  .refine((name) => !/[^A-Za-z 0-9-_]/g.test(name), {
    error: "Member name must use only characters 'A-Z', 'a-z', '0-9', and '-', '_', or ' '.",
  })
  .refine((name) => !/[ \-_]{2,}/g.test(name), {
    error: "Member name cannot contain more than 2 special characters '-', '_', or ' ' in a row.",
  })
  .refine((name) => name.length >= 1 && name.length <= 12, {
    error: ({ input }) => {
      if ((input as string).length === 0) return "Member name is required.";
      return "Member name must be between 1 and 12 characters.";
    },
  })
  .transform((name) => name.trim() as Member.Name);

const MemberNamesSchema = MemberNameSchema.array().nonempty();
const MemberCountSchema = z
  .string("Group size is required.")
  .transform((count) => parseInt(count))
  .refine((count) => Number.isSafeInteger(count))
  .refine((count) => count >= 2 && count <= 5, { error: "Group size must be between 2 and 5." });

type FormSubmissionResult =
  | {
      type: "Pending";
      groupNameErrors?: string[];
      memberErrors?: string[][];
      memberCountErrors?: string[];
      serverErrors?: string[];
    }
  | {
      type: "Success";
      credentials: GroupCredentials;
    };

const createGroupFormAction = async (formData: FormData): Promise<FormSubmissionResult> => {
  const groupNameRaw = formData.get("group-name");
  const memberNamesRaw = formData.getAll("member-name");
  const memberCountRaw = formData.get("group-member-count");

  const groupNameParsed = GroupNameSchema.safeParse(groupNameRaw);
  const memberCountParsed = MemberCountSchema.safeParse(memberCountRaw);
  const memberNamesParsed = MemberNamesSchema.safeParse(memberNamesRaw);

  if (!groupNameParsed.success || !memberCountParsed.success || !memberNamesParsed.success) {
    const errorResult: FormSubmissionResult = { type: "Pending" };
    if (!groupNameParsed.success) {
      errorResult.groupNameErrors = z.flattenError(groupNameParsed.error).formErrors;
    }
    if (!memberCountParsed.success) {
      errorResult.memberCountErrors = z.flattenError(memberCountParsed.error).formErrors;
    }
    if (!memberNamesParsed.success) {
      errorResult.memberErrors = Array(memberNamesRaw.length).fill([]);
      const members = z.treeifyError(memberNamesParsed.error).items;
      for (let i = 0; i < errorResult.memberErrors.length; i++) {
        const errors = members?.at(i)?.errors;
        if (!errors) continue;

        errorResult.memberErrors[i] = errors;
      }
    }

    return errorResult;
  }

  return Api.fetchCreateGroup(groupNameParsed.data, memberNamesParsed.data)
    .then((response) => new Promise<typeof response>((resolve) => setTimeout(() => resolve(response), 500)))
    .then((credentials) => {
      return { type: "Success", credentials } satisfies FormSubmissionResult;
    })
    .catch((reason) => {
      const error = reason instanceof Error ? reason.message : "Unknown error";
      return { type: "Pending", serverErrors: [error] };
    });
};

export const CreateGroupPage = (): ReactElement => {
  const navigate = useNavigate();
  const { logInLive } = useContext(APIContext) ?? {};
  const [memberCount, setMemberCount] = useState<number | undefined>(undefined);
  const [pending, setPending] = useState(false);
  const [formState, setFormState] = useState<FormSubmissionResult>({ type: "Pending" });

  const action = useCallback(
    (formData: FormData) => {
      setPending(true);
      if (formState?.type === "Pending") {
        setFormState({ ...formState, serverErrors: undefined });
      }
      createGroupFormAction(formData)
        .then((result) => {
          setFormState(result);
        })
        .catch((reason) => {
          console.error("Unexpected error during form submission:", reason);
        })
        .finally(() => {
          setPending(false);
        });
    },
    [formState],
  );

  /*
   * Intercept form reset, since for specifically <select> components, both
   * defaultValue and value are ignored upon the reset that occurs during form
   * submission.
   */
  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => {
    const watchReset = (e: Event): void => {
      e.preventDefault();
    };
    const form = formRef.current;
    if (!form) return;

    form.addEventListener("reset", watchReset);

    return (): void => {
      form.removeEventListener("reset", watchReset);
    };
  }, []);

  useEffect(() => {
    if (formState?.type !== "Success") return;

    const credentials = formState.credentials;

    logInLive?.(credentials)
      .then(() => navigate("/group/setup-instructions"))
      .catch((reason) => {
        console.error("CreateGroupPage: Failed to log in:", reason);
      });
  }, [formState, navigate, logInLive]);

  const groupNameInput = ((): ReactElement => {
    const groupNameErrors = formState?.type === "Pending" ? formState.groupNameErrors : undefined;
    const invalid = (groupNameErrors?.length ?? 0) > 0;

    return (
      <>
        <label htmlFor="create-group-group-name">Group name</label>
        <br />
        <input
          id="create-group-group-name"
          name="group-name"
          className={invalid ? "invalid" : "valid"}
          placeholder="Group name"
          maxLength={16}
        />
        <div className="validation-error">
          {groupNameErrors?.map((error, index) => (
            <Fragment key={error}>
              {index > 0 ? <br /> : undefined}
              {error}
            </Fragment>
          ))}
        </div>
      </>
    );
  })();

  const memberCountDropdown = ((): ReactElement => {
    const memberCountErrors = formState?.type === "Pending" ? formState.memberCountErrors : undefined;
    const invalid = (memberCountErrors?.length ?? 0) > 0;

    return (
      <>
        <label htmlFor="group-member-count">Group size</label>
        <br />
        <div className={`select-container rsborder-tiny rsbackground ${invalid ? "invalid" : "valid"}`}>
          <select
            id="group-member-count"
            name="group-member-count"
            defaultValue={0}
            onChange={({ target }) => {
              const newMemberCount = parseInt(target.options[target.selectedIndex].value);
              if (!Number.isSafeInteger(newMemberCount) || newMemberCount === memberCount) return;
              if (formState.type === "Pending") {
                const minSize = Math.min(memberCount ?? 0, newMemberCount);
                setFormState({ ...formState, memberErrors: formState.memberErrors?.slice(0, minSize) });
              }
              setMemberCount(newMemberCount);
            }}
          >
            <option value={0} disabled>
              Select an option
            </option>
            <option value={2}>2 Members</option>
            <option value={3}>3 Members</option>
            <option value={4}>4 Members</option>
            <option value={5}>5 Members</option>
          </select>
        </div>
        <div className="validation-error">
          {memberCountErrors?.map((error, index) => (
            <Fragment key={error}>
              {index > 0 ? <br /> : undefined}
              {error}
            </Fragment>
          ))}
        </div>
      </>
    );
  })();

  const memberNameInputs = [...Array(memberCount ?? 0).entries()].map((_, index) => {
    const errors = formState?.type === "Pending" ? formState?.memberErrors?.at(index) : undefined;
    const invalid = (errors?.length ?? 0) > 0;

    return (
      <Fragment key={index}>
        <label htmlFor={`create-group-member-name-${index}`}>Name for Member {index + 1}</label>
        <br />
        <input
          aria-required
          id={`create-group-member-name-${index}`}
          className={invalid ? "invalid" : "valid"}
          placeholder="Member name"
          name="member-name"
          maxLength={16}
        />
        <div className="validation-error">
          {errors?.map((string, index) => (
            <Fragment key={string}>
              {index > 0 ? <br /> : undefined}
              {string}
            </Fragment>
          ))}
        </div>
      </Fragment>
    );
  });

  const serverErrorsElement = ((): ReactNode => {
    if (formState.type !== "Pending" || (formState.serverErrors?.length ?? 0) < 1) return undefined;
    const errors = formState.serverErrors;
    return (
      <div className="validation-error">
        {" "}
        {errors?.map((string, index) => (
          <Fragment key={string}>
            {index > 0 ? <br /> : undefined}
            {string}
          </Fragment>
        ))}
      </div>
    );
  })();

  const pendingOverlay = pending ? (
    <div id="create-group-loading-overlay">
      <LoadingScreen />
    </div>
  ) : undefined;

  return (
    <div id="create-group-container">
      <form ref={formRef} id="create-group-window" className="rsborder rsbackground" action={action}>
        <div>
          <h3>Pick a name for your group</h3>
          <p>
            This does <span className="emphasize">not</span> need to be the in-game name.
          </p>
          {groupNameInput}
        </div>
        <div>
          <h3>What size is the group?</h3>
          <p>This can be changed later.</p>
          {memberCountDropdown}
        </div>
        {memberNameInputs.length > 0 ? (
          <div>
            <h3>Enter each members' name</h3>
            <p>
              This <span className="emphasize">does</span> need to match the in-game name. (Can be changed later)
            </p>
            {memberNameInputs}
          </div>
        ) : undefined}
        <button disabled={pending} className="men-button" type="submit">
          Create group
        </button>
        {serverErrorsElement}
        {pendingOverlay}
      </form>
    </div>
  );
};
