// resources/components/changelog-page/changelog-route.tsx
import { useContext, useEffect, useState, type ReactElement } from "react";
import { Context as APIContext } from "../../context/api-context";
import { AuthedLayout, UnauthedLayout } from "../layout/layout";
import { ChangelogPage } from "./changelog-page";

export const ChangelogRoute = (): ReactElement => {
  const { api, logInLive } = useContext(APIContext) ?? {};
  const [loginAttempted, setLoginAttempted] = useState(false);

  useEffect(() => {
    if (api || loginAttempted || !logInLive) return;

    logInLive()
      .catch(() => undefined)
      .finally(() => setLoginAttempted(true));
  }, [api, loginAttempted, logInLive]);

  const loggedIn = !!api;
  const page = (
    <ChangelogPage backHref={loggedIn ? "/group/items" : "/"} backLabel={loggedIn ? "Go to group" : "Back"} />
  );

  return loggedIn ? <AuthedLayout showPanels={false}>{page}</AuthedLayout> : <UnauthedLayout>{page}</UnauthedLayout>;
};

// resources/components/changelog-page/ChangelogRoute.vue
<script setup>
  import { computed } from "vue";
  import { useApiStore } from "../../stores/api";
  import AuthedLayout from "../layout/AuthedLayout.vue";
  import UnauthedLayout from "../layout/UnauthedLayout.vue";
  import ChangelogPage from "./ChangelogPage.vue";

  const apiStore = useApiStore();

  const loggedIn = computed(function isLoggedIn() {
    return Boolean(apiStore.client);
  });
</script>

<template>
  <AuthedLayout v-if="loggedIn" :show-panels="false">
    <ChangelogPage back-href="/group/items" back-label="Go to group" />
  </AuthedLayout>
  <UnauthedLayout v-else>
    <ChangelogPage back-href="/" back-label="Back" />
  </UnauthedLayout>
</template>
