// resources/components/changelog-page/changelog-page.tsx
import { useEffect, useState, type ReactElement } from "react";
import { AppLink } from "../app-link/app-link";
import { fetchChangelog, type Response as ChangelogResponse } from "../../api/requests/changelog";

import "./changelog-page.css";

export const ChangelogPage = ({ backHref, backLabel }: { backHref: string; backLabel: string }): ReactElement => {
  const [entries, setEntries] = useState<ChangelogResponse>();
  const [error, setError] = useState<string>();

  useEffect(() => {
    fetchChangelog({ baseURL: __API_URL__ })
      .then((response) => setEntries(response))
      .catch((reason) => {
        console.error("Failed to load changelog:", reason);
        setError("Failed to load changelog.");
      });
  }, []);

  return (
    <div id="changelog-page">
      <div id="changelog-header" className="rsbackground rsborder">
        <h2>Changelog</h2>
        <div className="changelog-actions">
          <AppLink href={backHref} className="small">
            {backLabel}
          </AppLink>
        </div>
      </div>

      {error ? (
        <div className="rsbackground rsborder changelog-entry">
          <p>{error}</p>
        </div>
      ) : null}

      {!entries && !error ? (
        <div className="rsbackground rsborder changelog-entry">
          <p>Loading…</p>
        </div>
      ) : null}

      {entries?.map((entry) => (
        <div key={entry.id} className="rsbackground rsborder changelog-entry">
          <div className="changelog-meta">
            <div className="changelog-title">{entry.title}</div>
            <div className="changelog-date">{entry.date}</div>
          </div>
          <div className="changelog-markdown" dangerouslySetInnerHTML={{ __html: entry.html }} />
        </div>
      ))}
    </div>
  );
};

// resources/components/changelog-page/ChangelogPage.vue
<script setup>
  import { onMounted, ref } from "vue";
  import { fetchChangelog } from "../../api/requests/changelog";
  import AppLink from "../app-link/AppLink.vue";
  import "./changelog-page.css";

  const props = defineProps({
    backHref: { type: String, required: true },
    backLabel: { type: String, required: true },
  });

  const entries = ref();
  const error = ref();

  onMounted(function loadChangelog() {
    fetchChangelog({ baseURL: __API_URL__ })
      .then(function storeChangelog(response) {
        entries.value = response;
      })
      .catch(function reportChangelogError(reason) {
        console.error("Failed to load changelog:", reason);
        error.value = "Failed to load changelog.";
      });
  });
</script>

<template>
  <div id="changelog-page">
    <div id="changelog-header" class="rsbackground rsborder">
      <h2>Changelog</h2>
      <div class="changelog-actions">
        <AppLink :href="props.backHref" class-name="small">{{ props.backLabel }}</AppLink>
      </div>
    </div>

    <div v-if="error" class="rsbackground rsborder changelog-entry">
      <p>{{ error }}</p>
    </div>

    <div v-else-if="!entries" class="rsbackground rsborder changelog-entry">
      <p>Loading…</p>
    </div>

    <div v-for="entry in entries" :key="entry.id" class="rsbackground rsborder changelog-entry">
      <div class="changelog-meta">
        <div class="changelog-title">{{ entry.title }}</div>
        <div class="changelog-date">{{ entry.date }}</div>
      </div>
      <div class="changelog-markdown" v-html="entry.html" />
    </div>
  </div>
</template>
