// resources/components/xp-dropper/xp-dropper.tsx
import { type ReactElement } from "react";
import type * as Member from "../../game/member";
import { SkillIconsBySkill } from "../../game/skill";
import { CachedImage } from "../cached-image/cached-image";

import "./xp-dropper.css";

/**
 * Displays rising XP drops in the style of OSRS.
 */
export const XpDropper = ({ xpDrops }: { xpDrops: Member.ExperienceDrop[] | undefined }): ReactElement => {
  return (
    <div className="xp-dropper">
      {xpDrops?.map(({ id, amounts, creationTimeMS }) => {
        const elements = [];
        for (const { skill, amount } of amounts) {
          elements.push(
            <div className="xp-dropper-drop" key={`${skill}-${amount}`}>
              <CachedImage alt={skill} src={SkillIconsBySkill[skill]} />
              {amount}
            </div>,
          );
        }
        return (
          <div className="xp-dropper-drop-cluster" key={`${id}-${creationTimeMS}`}>
            {elements}
          </div>
        );
      })}
    </div>
  );
};

// resources/components/xp-dropper/XpDropper.vue
<script setup>
  import { skillIcons } from "../../game/skill";
  import CachedImage from "../cached-image/CachedImage.vue";
  import "./xp-dropper.css";

  const props = defineProps({
    xpDrops: { type: Array, default: undefined },
  });
</script>

<template>
  <div class="xp-dropper">
    <div v-for="drop in props.xpDrops" :key="`${drop.id}-${drop.creationTimeMS}`" class="xp-dropper-drop-cluster">
      <div v-for="amount in drop.amounts" :key="`${amount.skill}-${amount.amount}`" class="xp-dropper-drop">
        <CachedImage :alt="amount.skill" :src="skillIcons[amount.skill]" />
        {{ amount.amount }}
      </div>
    </div>
  </div>
</template>
