// resources/components/items-page/ItemsPage.vue
<script setup>
  import { computed, ref, watch } from "vue";
  import * as Member from "../../game/member";
  import { useGameDataStore } from "../../stores/game-data";
  import { useGroupStore } from "../../stores/group";
  import { useSettingsStore } from "../../stores/settings";
  import { composeItemIconHref, mappedAlchable, mappedGEPrice, mappedHighAlch } from "../../game/items";
  import { useLocalStorage } from "../../composables/local-storage";
  import { useRememberedState } from "../../composables/remembered-state";
  import CachedImage from "../cached-image/CachedImage.vue";
  import Modal from "../modal/Modal.vue";
  import { useModal } from "../modal/use-modal";
  import SearchElement from "../search-element/SearchElement.vue";
  import { copyGearscapeItems } from "./gearscape-export";
  import ItemPanelsScrollArea from "./ItemPanelsScrollArea.vue";
  import ItemsPageTutorialWindow from "./ItemsPageTutorialWindow.vue";
  import "./items-page.css";

  const ItemSortCategories = [
    "Total quantity",
    "HA total value",
    "HA unit value",
    "GE total price",
    "GE unit price",
    "Alphabetical",
  ];
  const DEFAULT_SORT_CATEGORY = "GE total price";
  const DEFAULT_CONTAINER_FILTER = "All";

  const gameDataStore = useGameDataStore();
  const groupStore = useGroupStore();
  const settingsStore = useSettingsStore();

  const [searchFilterUserString, setSearchFilterUserString] = useRememberedState({
    key: "search-filter",
    defaultValue: undefined,
  });
  const [memberFilterUserString, setMemberFilterUserString] = useRememberedState({
    key: "items-page-member-filter",
    defaultValue: undefined,
  });
  const [sortCategory, setSortCategory] = useRememberedState({
    key: "items-page-sort-category",
    defaultValue: DEFAULT_SORT_CATEGORY,
  });
  const [containerFilter, setContainerFilter] = useRememberedState({
    key: "item-page-container-filter",
    defaultValue: DEFAULT_CONTAINER_FILTER,
  });
  const [pinnedItemsUserString, setPinnedItemsUserString] = useLocalStorage({
    key: "pinned-items",
    defaultValue: "",
    validator: validatePinnedItems,
  });
  const gearscapeExportStatus = ref("idle");
  const {
    open: tutorialModalOpen,
    componentProps: tutorialModalProps,
    openModal: openTutorialModal,
    closeModal: closeTutorialModal,
  } = useModal();

  const pinnedItems = computed(function getPinnedItems() {
    return new Set(
      pinnedItemsUserString.value
        .split(",")
        .filter(function hasIdentifier(identifier) {
          return identifier.length > 0;
        })
        .map(function parseIdentifier(identifier) {
          return Number.parseInt(identifier, 10);
        }),
    );
  });

  const searchParts = computed(function getSearchParts() {
    return (searchFilterUserString.value ?? "")
      .split("|")
      .map(function normalizeSearchPart(searchPart) {
        return searchPart.trim().toLocaleLowerCase();
      })
      .map(function parseSearchPart(searchPart) {
        if (searchPart.length === 0) {
          return { type: "Name", lowercase: "", exact: false };
        }

        const exact = searchPart.startsWith('"') && searchPart.endsWith('"');
        if (exact) {
          return { type: "Name", lowercase: searchPart.slice(1, -1), exact: true };
        }

        const splitForTag = searchPart.split(":");
        if (splitForTag.length === 1 || splitForTag[0] !== "tag") {
          return { type: "Name", lowercase: searchPart, exact: false };
        }

        const suffix = splitForTag.slice(1).join(":").toLocaleLowerCase();
        let bitmask = 0n;
        for (const [tag, bitIndex] of gameDataStore.gameData.itemTags?.tags ?? []) {
          if (tag.toLocaleLowerCase() === suffix) {
            bitmask += 1n << BigInt(bitIndex);
          }
        }

        return { type: "Tag", bitmask };
      })
      .filter(function hasSearchValue(searchPart) {
        return searchPart.type !== "Name" || searchPart.lowercase.length > 0;
      });
  });

  const memberFilter = computed(function getMemberFilter() {
    return new Set(
      (memberFilterUserString.value ?? "").split(",").filter(function isCurrentMember(name) {
        return name.length > 0 && groupStore.memberNames.has(name);
      }),
    );
  });

  const itemAggregates = computed(function getItemAggregates() {
    const aggregates = { totalHighAlch: 0, totalGEPrice: 0, filteredItems: [] };
    const itemData = gameDataStore.gameData.items;
    const grandExchangeData = gameDataStore.gameData.gePrices;
    const itemTags = gameDataStore.gameData.itemTags;

    for (const [itemID, breakdownByMember] of groupStore.items) {
      const itemDatum = itemData?.get(itemID);
      if (!itemDatum || !itemMatchesSearch(itemID, itemDatum, itemTags)) {
        continue;
      }

      const totalQuantity = getFilteredQuantity(breakdownByMember);
      if (totalQuantity <= 0) {
        continue;
      }

      const highAlch = mappedHighAlch(itemID, itemData);
      const alchable = mappedAlchable(itemID, itemData);
      const grandExchangePrice = mappedGEPrice(itemID, grandExchangeData, itemData);
      aggregates.totalHighAlch += totalQuantity * highAlch;
      aggregates.totalGEPrice += totalQuantity * grandExchangePrice;
      aggregates.filteredItems.push({
        itemID,
        itemName: itemDatum.name,
        breakdownByMember,
        totalQuantity,
        gePrice: grandExchangePrice,
        highAlch,
        alchable,
        imageURL: composeItemIconHref({ itemID, quantity: totalQuantity }, itemDatum),
      });
    }

    return aggregates;
  });

  const sortedItems = computed(function getSortedItems() {
    return [...itemAggregates.value.filteredItems].sort(function sortItems(leftItem, rightItem) {
      const leftItemIsPinned = pinnedItems.value.has(leftItem.itemID);
      const rightItemIsPinned = pinnedItems.value.has(rightItem.itemID);

      if (leftItemIsPinned !== rightItemIsPinned) {
        return leftItemIsPinned ? -1 : 1;
      }

      switch (sortCategory.value) {
        case "Total quantity":
          return rightItem.totalQuantity - leftItem.totalQuantity;
        case "HA total value":
          return rightItem.highAlch * rightItem.totalQuantity - leftItem.highAlch * leftItem.totalQuantity;
        case "HA unit value":
          return rightItem.highAlch - leftItem.highAlch;
        case "GE total price":
          return rightItem.gePrice * rightItem.totalQuantity - leftItem.gePrice * leftItem.totalQuantity;
        case "GE unit price":
          return rightItem.gePrice - leftItem.gePrice;
        case "Alphabetical":
          return leftItem.itemName.localeCompare(rightItem.itemName);
      }
    });
  });

  const hasActiveFilters = computed(function filtersAreActive() {
    return (
      searchParts.value.length > 0 ||
      memberFilter.value.size > 0 ||
      sortCategory.value !== DEFAULT_SORT_CATEGORY ||
      containerFilter.value !== DEFAULT_CONTAINER_FILTER
    );
  });

  const gearscapeExportLabel = computed(function getGearscapeExportLabel() {
    return {
      idle: "Copy for Gearscape",
      success: "Copied for Gearscape",
      error: "Copy failed",
    }[gearscapeExportStatus.value];
  });

  function validatePinnedItems(value) {
    return value;
  }

  function validateContainerFilter(value) {
    return value === "All" || Member.itemContainerNames.includes(value) ? value : undefined;
  }

  function itemMatchesSearch(itemID, itemDatum, itemTags) {
    if (searchParts.value.length === 0) {
      return true;
    }

    const itemLowercase = itemDatum.name.toLocaleLowerCase();

    return searchParts.value.some(function matchesSearchPart(searchPart) {
      if (searchPart.type === "Name") {
        return searchPart.exact ? searchPart.lowercase === itemLowercase : itemLowercase.includes(searchPart.lowercase);
      }

      return (searchPart.bitmask & (itemTags?.items[itemID] ?? 0n)) !== 0n;
    });
  }

  function getFilteredQuantity(breakdownByMember) {
    let totalQuantity = 0;

    for (const [name, breakdown] of breakdownByMember) {
      if (memberFilter.value.has(name)) {
        continue;
      }

      for (const itemContainer of Member.itemContainerNames) {
        if (containerFilter.value === "All" || containerFilter.value === itemContainer) {
          totalQuantity += breakdown[itemContainer] ?? 0;
        }
      }
    }

    return totalQuantity;
  }

  function togglePin(itemID) {
    const newPinnedItems = new Set(pinnedItems.value);

    if (newPinnedItems.has(itemID)) {
      newPinnedItems.delete(itemID);
    } else {
      newPinnedItems.add(itemID);
    }

    setPinnedItemsUserString([...newPinnedItems].join(","));
  }

  function toggleMember(name) {
    const newMemberFilter = new Set(memberFilter.value);

    if (newMemberFilter.has(name)) {
      newMemberFilter.delete(name);
    } else {
      newMemberFilter.add(name);
    }

    setMemberFilterUserString([...newMemberFilter].join(","));
  }

  function resetFilters() {
    setSearchFilterUserString(undefined);
    setMemberFilterUserString(undefined);
    setSortCategory(undefined);
    setContainerFilter(undefined);
  }

  async function copyItemsForGearscape() {
    try {
      await copyGearscapeItems(sortedItems.value);
      gearscapeExportStatus.value = "success";
    } catch (reason) {
      console.error("Failed to copy items for Gearscape:", reason);
      gearscapeExportStatus.value = "error";
    }
  }

  watch(
    [
      memberFilterUserString,
      function getMemberNames() {
        return groupStore.memberNames;
      },
    ],
    function removeMissingMembers() {
      const normalizedFilter = [...memberFilter.value].join(",");
      if ((memberFilterUserString.value ?? "") !== normalizedFilter) {
        setMemberFilterUserString(normalizedFilter || undefined);
      }
    },
    { immediate: true },
  );

  watch(gearscapeExportStatus, function resetGearscapeExportStatus(status, _previousStatus, onCleanup) {
    if (status === "idle") {
      return;
    }

    const timeout = window.setTimeout(function resetStatus() {
      gearscapeExportStatus.value = "idle";
    }, 3000);
    onCleanup(function clearResetTimeout() {
      window.clearTimeout(timeout);
    });
  });
</script>

<template>
  <Modal
    :open="tutorialModalOpen"
    :component="ItemsPageTutorialWindow"
    :component-props="tutorialModalProps"
    @close="closeTutorialModal"
  />

  <div v-if="groupStore.items.size <= 0" id="items-page-no-items" class="rsborder rsbackground">
    <h3>Your group has no recorded items!</h3>
    <p>
      Either no members have logged in with the plugin, or there is an issue. Please double check that the names in the
      <RouterLink to="../settings" class="orange-link">settings</RouterLink> page
      <span class="emphasize">exactly</span> match your group members' in-game display names.
    </p>
  </div>

  <template v-else>
    <div id="items-page-head">
      <SearchElement
        id="items-page-search"
        placeholder="Search"
        :value="searchFilterUserString ?? ''"
        :default-value="searchFilterUserString"
        @change="setSearchFilterUserString"
      />
      <button
        v-if="hasActiveFilters"
        id="items-page-reset-filters-button"
        class="men-button"
        data-tooltip="Reset all filters to default"
        aria-label="Reset all filters to default"
        @click="resetFilters"
      >
        <CachedImage alt="Reset filters" src="/ui/1731-0.png" />
        Reset
      </button>
      <button id="items-page-tutorial-button" class="men-button" @click="openTutorialModal()">
        <CachedImage alt="Items tutorial" src="/ui/1094-0.png" />
        Tutorial
      </button>
    </div>

    <div class="items-page-utility">
      <select
        class="rsborder-tiny rsbackground rsbackground-hover"
        :value="sortCategory"
        @change="setSortCategory($event.target.value)"
      >
        <option v-for="category in ItemSortCategories" :key="category" :value="category">
          {{ `Sort: ${category}` }}
        </option>
      </select>
      <select
        class="rsborder-tiny rsbackground rsbackground-hover"
        :value="containerFilter"
        @change="setContainerFilter(validateContainerFilter($event.target.value))"
      >
        <option v-for="name in ['All', ...Member.itemContainerNames]" :key="name" :value="name">{{ name }}</option>
      </select>
      <div class="items-page-member-filter-clipbox rsborder-tiny rsbackground" style="overflow: hidden">
        <span class="items-page-member-filter-container">
          <span v-for="name in groupStore.memberNames" :key="name" class="rsbackground-hover">
            <input
              :id="`items-page-member-filter-${name}`"
              type="checkbox"
              :checked="!memberFilter.has(name)"
              @change="toggleMember(name)"
            />
            <label :for="`items-page-member-filter-${name}`">{{ name }}</label>
          </span>
        </span>
      </div>
    </div>

    <div class="items-page-utility">
      <span class="rsborder-tiny rsbackground rsbackground-hover">
        <span>{{ itemAggregates.filteredItems.length.toLocaleString() }}</span
        >&nbsp;<span>items</span>
      </span>
      <button
        v-if="settingsStore.enableGearscapeExport"
        id="items-page-gearscape-export-button"
        class="men-button men-button-small"
        data-tooltip="Copy only the currently filtered items to the clipboard for importing into Gearscape"
        aria-label="Copy current items to clipboard for Gearscape"
        @click="copyItemsForGearscape"
      >
        {{ gearscapeExportLabel }}
      </button>
      <span class="rsborder-tiny rsbackground rsbackground-hover">
        HA:&nbsp;<span>{{ itemAggregates.totalHighAlch.toLocaleString() }}</span
        ><span>gp</span>
      </span>
      <span class="rsborder-tiny rsbackground rsbackground-hover">
        GE:&nbsp;<span>{{ itemAggregates.totalGEPrice.toLocaleString() }}</span
        ><span>gp</span>
      </span>
    </div>

    <ItemPanelsScrollArea
      :sorted-items="sortedItems"
      :member-filter="memberFilter"
      :container-filter="containerFilter"
      :pinned-items="pinnedItems"
      @toggle-pin="togglePin"
    />
  </template>
</template>

// resources/components/items-page/items-page.tsx
import { type ReactElement, Fragment, memo, useContext, useEffect, useRef, useState, useCallback } from "react";
import { SearchElement } from "../search-element/search-element";
import * as Member from "../../game/member";
import { GameDataContext } from "../../context/game-data-context";
import { type ItemID, mappedAlchable, mappedGEPrice, mappedHighAlch, composeItemIconHref } from "../../game/items";
import { GroupItemsContext, GroupMemberNamesContext } from "../../context/group-context";
import { Link } from "react-router-dom";
import { useItemsPriceTooltip } from "./items-page-tooltip";
import { useItemsBreakdownTooltip } from "./items-breakdown-tooltip";
import { useVirtualizer } from "@tanstack/react-virtual";
import { CachedImage } from "../cached-image/cached-image";
import { formatTitle } from "../../ts/format-title";
import { useLocalStorage } from "../../hooks/local-storage";
import { useModal } from "../modal/modal";
import { copyGearscapeItems } from "./gearscape-export";
import { SettingsContext } from "../../context/settings-context";

import "./items-page.css";

// Negate the filter, so that new/renamed members aren't filtered by default
type MemberNegativeFilter = Set<Member.Name>;

const ItemSortCategory = [
  "Total quantity",
  "HA total value",
  "HA unit value",
  "GE total price",
  "GE unit price",
  "Alphabetical",
] as const;
type ItemSortCategory = (typeof ItemSortCategory)[number];

const DEFAULT_SORT_CATEGORY: ItemSortCategory = "GE total price";

interface ItemPanelProps {
  itemName: string;
  itemID: ItemID;
  highAlchPer: number;
  alchable: boolean;
  gePricePer: number;
  imageURL: string;
  totalQuantity: number;
  memberFilter: MemberNegativeFilter;
  containerFilter: Member.ItemContainer | "All";
  quantities: Map<Member.Name, Member.ItemLocationBreakdown>;
  isPinned: boolean;
  onTogglePin: (itemID: ItemID) => void;
}

// Memo works well here since all the props are primitives, except for
// `quantities` for which we guarantee referential stability in
// group-context.ts.
const ItemPanel = memo(
  ({
    itemName,
    itemID,
    highAlchPer,
    alchable,
    gePricePer,
    imageURL,
    totalQuantity,
    memberFilter,
    containerFilter,
    quantities,
    isPinned,
    onTogglePin,
  }: ItemPanelProps): ReactElement => {
    const { tooltipElement, hideTooltip, showTooltip } = useItemsPriceTooltip();
    const {
      tooltipElement: breakdownTooltip,
      hideTooltip: hideBreakdownTooltip,
      showTooltip: showBreakdownTooltip,
    } = useItemsBreakdownTooltip();

    const quantityBreakdown = [...quantities]
      .filter(([name]) => !memberFilter.has(name))
      .map(([name, breakdown]) => {
        let quantity = 0;

        for (const itemContainer of Member.ItemContainer) {
          if (containerFilter !== "All" && containerFilter !== itemContainer) continue;

          quantity += breakdown[itemContainer] ?? 0;
        }

        return { name, quantity, breakdown };
      })
      .filter(({ quantity }) => quantity > 0)
      .map(({ name, quantity, breakdown }) => {
        const quantityPercent = (quantity / totalQuantity) * 100;
        const onPointerEnter = (): void => {
          if (containerFilter !== "All") {
            return;
          }
          showBreakdownTooltip({
            name,
            filter: containerFilter,
            breakdown,
          });
        };
        return (
          <Fragment key={name}>
            <span onPointerEnter={onPointerEnter}>{name}</span>
            <span onPointerEnter={onPointerEnter}>{quantity.toLocaleString()}</span>
            <span
              className="items-page-panel-quantity-contribution"
              onPointerEnter={onPointerEnter}
              style={{ transform: `scaleX(${quantityPercent}%)`, background: `hsl(${quantityPercent}, 100%, 40%)` }}
            />
          </Fragment>
        );
      });

    const highAlch = highAlchPer * totalQuantity;
    const gePrice = gePricePer * totalQuantity;

    const wikiLink = `https://oldschool.runescape.wiki/w/Special:Lookup?type=item&id=${itemID}`;

    return (
      <div className={`items-page-panel rsborder rsbackground ${isPinned ? "items-page-panel-pinned" : ""}`}>
        <div className="items-page-panel-top rsborder-tiny">
          <div>
            <Link className="items-page-panel-name rstext" to={wikiLink} target="_blank" rel="noopener noreferrer">
              {itemName}
            </Link>
            <button
              className={`items-page-panel-pin-button ${isPinned ? "pinned" : ""}`}
              onClick={() => onTogglePin(itemID)}
              title={isPinned ? "Unpin item" : "Pin item to top"}
              aria-label={isPinned ? "Unpin item" : "Pin item to top"}
            >
              {isPinned ? "★" : "☆"}
            </button>
            <div className="items-page-panel-item-details">
              <span>Quantity</span>
              <span>{totalQuantity.toLocaleString()}</span>
              <span>High alch</span>
              <span
                onPointerEnter={
                  alchable
                    ? (): void =>
                        showTooltip({
                          perPiecePrice: highAlchPer,
                          totalPrice: highAlch,
                          quantity: totalQuantity,
                        })
                    : undefined
                }
                onPointerLeave={alchable ? hideTooltip : undefined}
              >
                {alchable ? `${highAlch.toLocaleString()}gp` : "n/a"}
              </span>
              <span>GE price</span>
              <span
                onPointerEnter={
                  gePricePer > 0
                    ? (): void =>
                        showTooltip({
                          perPiecePrice: gePricePer,
                          totalPrice: gePrice,
                          quantity: totalQuantity,
                        })
                    : undefined
                }
                onPointerLeave={gePricePer > 0 ? hideTooltip : undefined}
              >
                {gePricePer > 0 ? `${gePrice.toLocaleString()}gp` : "n/a"}
              </span>
            </div>
          </div>
          <CachedImage
            loading="lazy"
            className="items-page-panel-icon"
            alt={itemName ?? "An unknown item"}
            src={imageURL}
          />
        </div>
        <div className="items-page-panel-quantity-breakdown" onPointerLeave={hideBreakdownTooltip}>
          {quantityBreakdown}
        </div>
        {tooltipElement}
        {breakdownTooltip}
      </div>
    );
  },
);

interface FilteredItem {
  itemID: ItemID;
  itemName: string;
  imageURL: string;
  breakdownByMember: Map<Member.Name, Member.ItemLocationBreakdown>;
  totalQuantity: number;
  gePrice: number;
  highAlch: number;
  alchable: boolean;
}

// Defines the minimal width of each column, which the panels flex to fill
const PANEL_WIDTH_PIXELS = 280;

const ItemPanelsScrollArea = ({
  sortedItems,
  memberFilter,
  containerFilter,
  pinnedItems,
  onTogglePin,
}: {
  sortedItems: FilteredItem[];
  memberFilter: MemberNegativeFilter;
  containerFilter: Member.ItemContainer | "All";
  pinnedItems: Set<ItemID>;
  onTogglePin: (itemID: ItemID) => void;
}): ReactElement => {
  const parentRef = useRef<HTMLDivElement>(null);
  const childRef = useRef<HTMLDivElement>(null);
  const [columns, setColumns] = useState(3);
  const itemsVirtualizer = useVirtualizer({
    count: Math.ceil(sortedItems.length / columns),
    getScrollElement: () => parentRef.current,
    overscan: 3,
    estimateSize: () => 220,
  });

  useEffect(() => {
    const updateColumnsFromDivWidth = (): void => {
      const newColumns = Math.floor((childRef.current?.scrollWidth ?? 0) / PANEL_WIDTH_PIXELS);
      if (newColumns < 1) {
        setColumns(1);
        return;
      }

      setColumns(newColumns);
    };
    window.addEventListener("resize", updateColumnsFromDivWidth);

    updateColumnsFromDivWidth();

    return (): void => {
      window.removeEventListener("resize", updateColumnsFromDivWidth);
    };
  }, []);

  return (
    <div ref={parentRef} style={{ overflowY: "auto", paddingRight: "12px" }}>
      <div
        ref={childRef}
        style={{ height: `${itemsVirtualizer.getTotalSize()}px`, width: "100%", position: "relative" }}
      >
        {itemsVirtualizer.getVirtualItems().map((rowOfItems) => {
          const items = sortedItems.slice(rowOfItems.index * columns, (rowOfItems.index + 1) * columns);

          return (
            <div
              key={rowOfItems.key}
              data-index={rowOfItems.index}
              ref={itemsVirtualizer.measureElement}
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                right: 0,
                transform: `translateY(${rowOfItems.start - itemsVirtualizer.options.scrollMargin}px)`,
                display: "grid",
                gridTemplateColumns: `repeat(${columns}, 1fr)`,
              }}
            >
              {items.map((item) => (
                <ItemPanel
                  key={item.itemID}
                  itemID={item.itemID}
                  imageURL={item.imageURL}
                  totalQuantity={item.totalQuantity}
                  highAlchPer={item.highAlch}
                  alchable={item.alchable}
                  gePricePer={item.gePrice}
                  itemName={item.itemName}
                  memberFilter={memberFilter}
                  containerFilter={containerFilter}
                  quantities={item.breakdownByMember}
                  isPinned={pinnedItems.has(item.itemID)}
                  onTogglePin={onTogglePin}
                />
              ))}
            </div>
          );
        })}
      </div>
    </div>
  );
};

const validateItemSortCategory = (value: string | undefined): ItemSortCategory | undefined => {
  if (typeof value !== "string") return undefined;
  if (!ItemSortCategory.includes(value as ItemSortCategory)) return undefined;

  return value as ItemSortCategory;
};

type PinnedItems = Set<ItemID>;
const validatePinnedItems = (value: string | undefined): string | undefined => value;
const usePinnedItems = (): [PinnedItems, (toggleID: ItemID) => void] => {
  const [pinnedItemsUserString, setPinnedItemsUserString] = useLocalStorage({
    key: "pinned-items",
    defaultValue: "",
    validator: validatePinnedItems,
  });

  const pinnedItems = new Set<ItemID>(
    pinnedItemsUserString
      .split(",")
      .filter((id) => id.length > 0)
      .map((id) => parseInt(id, 10) as ItemID),
  );

  const togglePin = useCallback(
    (itemID: ItemID) => {
      const newPinnedItems = new Set(pinnedItems);
      if (newPinnedItems.has(itemID)) {
        newPinnedItems.delete(itemID);
      } else {
        newPinnedItems.add(itemID);
      }
      setPinnedItemsUserString(Array.from(newPinnedItems).join(","));
    },
    [pinnedItems, setPinnedItemsUserString],
  );

  return [pinnedItems, togglePin];
};

type ContainerFilter = "All" | Member.ItemContainer;
const DEFAULT_CONTAINER_FILTER: ContainerFilter = "All";
const validateContainerFilter = (value: string | undefined): ContainerFilter | undefined => {
  if (typeof value !== "string") return undefined;
  if (value !== "All" && !Member.ItemContainer.includes(value as Member.ItemContainer)) return undefined;

  return value as ContainerFilter;
};

interface SearchFilter {
  parts: (
    | {
        type: "Name";
        lowercase: string;
        exact: boolean;
      }
    | { type: "Tag"; bitmask: bigint }
  )[];
}
const validateSearchFilter = (value: string | undefined): string | undefined => value;
const useSearchFilter = (): [ReactElement, SearchFilter, () => void] => {
  const [filterUserString, setFilterUserString] = useLocalStorage({
    key: "search-filter",
    defaultValue: undefined,
    validator: validateSearchFilter,
  });
  const { itemTags } = useContext(GameDataContext);

  const parts = (filterUserString ?? "")
    .split("|")
    .map((s: string) => {
      return s.trim().toLocaleLowerCase();
    })
    .map<SearchFilter["parts"][number]>((s: string) => {
      if (s.length === 0) {
        return {
          type: "Name",
          lowercase: "",
          exact: false,
        };
      }

      const exact = s.startsWith('"') && s.endsWith('"');
      if (exact) {
        return {
          type: "Name",
          lowercase: s.slice(1, -1),
          exact: true,
        };
      }

      const splitForTag = s.split(":");
      const prefix = splitForTag[0];
      if (splitForTag.length === 1 || prefix !== "tag") {
        return {
          type: "Name",
          lowercase: s,
          exact: false,
        };
      }

      if (itemTags?.tags === undefined) {
        return {
          type: "Tag",
          bitmask: 0n,
        };
      }

      const suffix = splitForTag.slice(1).join(":").toLocaleLowerCase();

      let bitmask = 0n;
      for (const [tag, bitIndex] of itemTags?.tags ?? []) {
        const tagMatches = tag.toLocaleLowerCase() === suffix;
        if (tagMatches) {
          bitmask += 1n << BigInt(bitIndex);
        }
      }

      return {
        type: "Tag" as const,
        bitmask,
      };
    })
    .filter((part) => {
      if (part.type !== "Name") {
        return true;
      }
      return part.lowercase.length > 0;
    });

  const resetSearch = useCallback(() => {
    setFilterUserString(undefined);
  }, [setFilterUserString]);

  return [
    <SearchElement
      onChange={setFilterUserString}
      id="items-page-search"
      placeholder="Search"
      auto-focus
      value={filterUserString ?? ""}
      defaultValue={filterUserString}
    />,
    { parts },
    resetSearch,
  ];
};

const validateMemberFilter = (value: string | undefined): string | undefined => value;
const useMemberFilter = (): [ReactElement, MemberNegativeFilter, () => void] => {
  const [memberFilterUserString, setMemberFilterUserString] = useLocalStorage({
    key: "items-page-member-filter",
    defaultValue: undefined,
    validator: validateMemberFilter,
  });

  const members = useContext(GroupMemberNamesContext);

  const memberFilterRef = useRef<MemberNegativeFilter>(new Set());
  useEffect(() => {
    const newFilter = new Set(
      (memberFilterUserString ?? "").split(",").filter((name) => name.length > 0) as Member.Name[],
    );
    memberFilterRef.current = newFilter;
    if (members.size > 0) {
      memberFilterRef.current = memberFilterRef.current.intersection(members);
    }
    setMemberFilterUserString([...memberFilterRef.current.values()].join(","));
  }, [memberFilterUserString]);

  const element = (
    <div className="items-page-member-filter-clipbox rsborder-tiny rsbackground" style={{ overflow: "hidden" }}>
      <span className="items-page-member-filter-container">
        {[...members.values()].map((name) => (
          <Fragment key={name}>
            <span className="rsbackground-hover">
              <input
                id={`items-page-member-filter-${name}`}
                type="checkbox"
                checked={!memberFilterRef.current.has(name)}
                onChange={() => {
                  const shouldDelete = memberFilterRef.current.has(name);
                  const newFilter = new Set(memberFilterRef.current.values());
                  if (shouldDelete) {
                    newFilter.delete(name);
                  } else {
                    newFilter.add(name);
                  }

                  memberFilterRef.current = newFilter;
                  if (members.size > 0) {
                    memberFilterRef.current = memberFilterRef.current.intersection(members);
                  }
                  setMemberFilterUserString([...memberFilterRef.current.values()].join(","));
                }}
              />
              <label htmlFor={`items-page-member-filter-${name}`}>{name}</label>
            </span>
          </Fragment>
        ))}
      </span>
    </div>
  );

  const resetMemberFilter = useCallback(() => {
    setMemberFilterUserString(undefined);
  }, [setMemberFilterUserString]);

  return [element, memberFilterRef.current, resetMemberFilter];
};

const ItemsPageTutorialWindow = ({ onCloseModal }: { onCloseModal: () => void }): ReactElement => {
  const { itemTags } = useContext(GameDataContext);
  const [pinned, setPinned] = useState(true);

  return (
    <div className="items-page-tutorial-window rsborder rsbackground">
      <div className="items-page-tutorial-window-header">
        <button onClick={onCloseModal}>
          <CachedImage src="/ui/1731-0.png" alt={formatTitle("Close dialog")} title={formatTitle("Close dialog")} />
        </button>
      </div>
      <div className="items-page-tutorial-window-body">
        <h2>{formatTitle("Searching for items")}</h2>
        <p>Type in the 'Search' box to search item names, and display only the items that match.</p>
        <p>
          {`The match is not exact, unless the phrase is surrounded by double quotes. For example, searching `}
          <span className="items-page-tutorial-inline-search">coal</span>
          {` will display both the OSRS items `}
          <b className="items-page-tutorial-inline-item-name">Coal</b> and{" "}
          <b className="items-page-tutorial-inline-item-name">Coal bag</b>
          {`, while searching instead `}
          <span className="items-page-tutorial-inline-search">"coal"</span>
          {` will display only `}
          <b className="items-page-tutorial-inline-item-name">Coal</b>. Searches are never case-sensitive.
        </p>
        <p>
          {` You can combine searches separated with vertical bars to search for items that match any of the searches. For example, `}
          <span className="items-page-tutorial-inline-search">whip | coal</span> will display both{" "}
          <b className="items-page-tutorial-inline-item-name">Abyssal Whip</b>
          {` and `}
          <b className="items-page-tutorial-inline-item-name">Coal bag</b> (among other items).
        </p>
        <p>
          Type <span className="items-page-tutorial-inline-search">tag:</span> followed by an exact tag to search by
          category of item instead of name. The following tags are available, with some entries being aliases that
          contain the same items:
        </p>
        <div className="items-page-tutorial-tags rsborder-tiny">
          {itemTags?.tags.map(([tag]) => (
            <span key={tag}>{tag}</span>
          ))}
        </div>
        <h2>{formatTitle("Item breakdown")}</h2>
        <ItemPanel
          containerFilter="All"
          gePricePer={200}
          highAlchPer={100}
          alchable={true}
          imageURL="/item-icons/4323.webp"
          isPinned={pinned}
          itemID={4323 as ItemID}
          itemName="Team-5 cape"
          memberFilter={new Set()}
          onTogglePin={() => {
            setPinned(!pinned);
          }}
          quantities={new Map([["Zezima" as Member.Name, { Total: 100, Bank: 100, Inventory: 15 }]])}
          totalQuantity={115}
        />
        <ul>
          <li>
            Hover over the numbers to see detailed tooltips, including a breakdown of where items are for each member.
          </li>
          <li>
            Hover over the upper right of the panel and click the star (★) to pin the item, causing it to appear before
            all other items regardless of sorting order.
          </li>
          <li>The name is an interactive link that leads to the item's page on the official OSRS wiki.</li>
        </ul>
      </div>
    </div>
  );
};

export const ItemsPage = (): ReactElement => {
  const [searchInputElement, searchFilter, resetSearchFilter] = useSearchFilter();
  const [memberFilterElement, memberFilter, resetMemberFilter] = useMemberFilter();
  const [gearscapeExportStatus, setGearscapeExportStatus] = useState<"idle" | "success" | "error">("idle");

  const [pinnedItems, togglePin] = usePinnedItems();

  const [sortCategory, setSortCategory] = useLocalStorage<ItemSortCategory>({
    key: "items-page-sort-category",
    defaultValue: DEFAULT_SORT_CATEGORY,
    validator: validateItemSortCategory,
  });

  const { gePrices: geData, items: itemData, itemTags } = useContext(GameDataContext);
  const items = useContext(GroupItemsContext);
  const { enableGearscapeExport } = useContext(SettingsContext);
  const { open: openSearchTutorial, modal: searchTutorialModal } = useModal(ItemsPageTutorialWindow);

  const [containerFilter, setContainerFilter] = useLocalStorage<ContainerFilter>({
    key: "item-page-container-filter",
    defaultValue: DEFAULT_CONTAINER_FILTER,
    validator: validateContainerFilter,
  });

  useEffect(() => {
    if (gearscapeExportStatus === "idle") {
      return;
    }

    const timeout = window.setTimeout(() => {
      setGearscapeExportStatus("idle");
    }, 3000);

    return (): void => {
      window.clearTimeout(timeout);
    };
  }, [gearscapeExportStatus]);

  const resetFilters = useCallback(() => {
    resetSearchFilter();
    resetMemberFilter();
    setSortCategory(undefined);
    setContainerFilter(undefined);
  }, [resetSearchFilter, resetMemberFilter, setSortCategory, setContainerFilter]);

  const hasActiveFilters =
    searchFilter.parts.length > 0 ||
    memberFilter.size > 0 ||
    sortCategory !== DEFAULT_SORT_CATEGORY ||
    containerFilter !== DEFAULT_CONTAINER_FILTER;

  interface ItemAggregates {
    totalHighAlch: number;
    totalGEPrice: number;
    filteredItems: FilteredItem[];
  }

  const { totalHighAlch, totalGEPrice, filteredItems } = [...(items ?? [])].reduce<ItemAggregates>(
    (previousValue, [itemID, breakdownByMember]) => {
      const itemDatum = itemData?.get(itemID);

      if (!itemDatum) return previousValue;

      if (searchFilter.parts.length > 0) {
        const itemLowercase = itemDatum.name.toLocaleLowerCase();
        const matches = searchFilter.parts.some((part) => {
          switch (part.type) {
            case "Name": {
              if (part.exact) {
                return part.lowercase === itemLowercase;
              } else {
                return itemLowercase.includes(part.lowercase);
              }
            }
            case "Tag": {
              return (part.bitmask & (itemTags?.items[itemID] ?? 0n)) !== 0n;
            }
          }
        });

        if (!matches) {
          return previousValue;
        }
      }

      let filteredTotalQuantity = 0;
      for (const [name, breakdown] of breakdownByMember) {
        if (memberFilter.has(name)) continue;

        for (const itemContainer of Member.ItemContainer) {
          if (containerFilter !== "All" && containerFilter !== itemContainer) continue;

          filteredTotalQuantity += breakdown[itemContainer] ?? 0;
        }
      }

      if (filteredTotalQuantity <= 0) return previousValue;

      const highAlch = mappedHighAlch(itemID, itemData);
      const alchable = mappedAlchable(itemID, itemData);
      const gePrice = mappedGEPrice(itemID, geData, itemData);
      previousValue.totalHighAlch += filteredTotalQuantity * highAlch;
      previousValue.totalGEPrice += filteredTotalQuantity * gePrice;

      previousValue.filteredItems.push({
        itemID,
        itemName: itemDatum?.name ?? "@UNKNOWN",
        breakdownByMember,
        totalQuantity: filteredTotalQuantity,
        gePrice,
        highAlch,
        alchable,
        imageURL: composeItemIconHref({ itemID, quantity: filteredTotalQuantity }, itemDatum),
      });

      return previousValue;
    },
    { totalHighAlch: 0, totalGEPrice: 0, filteredItems: [] },
  );

  const sortedItems = [...filteredItems].sort((lhs, rhs) => {
    const lhsIsPinned = pinnedItems.has(lhs.itemID);
    const rhsIsPinned = pinnedItems.has(rhs.itemID);

    if (lhsIsPinned && !rhsIsPinned) return -1;
    if (!lhsIsPinned && rhsIsPinned) return 1;

    switch (sortCategory) {
      case "Total quantity":
        return rhs.totalQuantity - lhs.totalQuantity;
      case "HA total value":
        return rhs.highAlch * rhs.totalQuantity - lhs.highAlch * lhs.totalQuantity;
      case "HA unit value":
        return rhs.highAlch - lhs.highAlch;
      case "GE total price":
        return rhs.gePrice * rhs.totalQuantity - lhs.gePrice * lhs.totalQuantity;
      case "GE unit price":
        return rhs.gePrice - lhs.gePrice;
      case "Alphabetical":
        return lhs.itemName.localeCompare(rhs.itemName);
    }
  });

  async function copyItemsForGearscape(): Promise<void> {
    try {
      await copyGearscapeItems(sortedItems);
      setGearscapeExportStatus("success");
    } catch (reason) {
      console.error("Failed to copy items for Gearscape:", reason);
      setGearscapeExportStatus("error");
    }
  }

  const gearscapeExportLabel = {
    idle: "Copy for Gearscape",
    success: "Copied for Gearscape",
    error: "Copy failed",
  }[gearscapeExportStatus];

  if ((items?.size ?? 0) <= 0) {
    return (
      <div id="items-page-no-items" className="rsborder rsbackground">
        <h3>{formatTitle("Your group has no recorded items!")}</h3>
        <p>
          Either no members have logged in with the plugin, or there is an issue. Please double check that the names in
          the{" "}
          <Link to="../settings" className="orange-link">
            settings
          </Link>{" "}
          page <span className="emphasize">exactly</span> match your group members' in-game display names.
        </p>
      </div>
    );
  }

  return (
    <>
      {searchTutorialModal}

      <div id="items-page-head">
        {searchInputElement}
        {hasActiveFilters ? (
          <button
            id="items-page-reset-filters-button"
            className="men-button"
            onClick={resetFilters}
            title="Reset all filters to default"
            aria-label="Reset all filters to default"
          >
            <CachedImage alt={"Reset filters"} src="/ui/1731-0.png" />
            Reset
          </button>
        ) : undefined}
        <button id="items-page-tutorial-button" className="men-button" onClick={openSearchTutorial}>
          <CachedImage alt={"items tutorial"} src="/ui/1094-0.png" />
          Tutorial
        </button>
      </div>
      <div className="items-page-utility">
        <select
          className="rsborder-tiny rsbackground rsbackground-hover"
          value={sortCategory}
          onChange={(e) => {
            const newCategory = e.target.value as ItemSortCategory;
            setSortCategory(newCategory);
          }}
        >
          {ItemSortCategory.map((category) => (
            <option key={category} value={category}>
              {`Sort: ${formatTitle(category)}`}
            </option>
          ))}
        </select>
        <select
          className="rsborder-tiny rsbackground rsbackground-hover"
          value={containerFilter}
          onChange={(e) => {
            setContainerFilter(validateContainerFilter(e.target.value));
          }}
        >
          {["All", ...Member.ItemContainer].map((name) => (
            <option key={name} value={name}>
              {name}
            </option>
          ))}
        </select>
        {memberFilterElement}
      </div>
      <div className="items-page-utility">
        <span className="rsborder-tiny rsbackground rsbackground-hover">
          <span>{filteredItems.length.toLocaleString()}</span>&nbsp;
          <span>items</span>
        </span>
        {enableGearscapeExport ? (
          <button
            id="items-page-gearscape-export-button"
            className="men-button men-button-small"
            onClick={copyItemsForGearscape}
            title="Copy only the currently filtered items to the clipboard for importing into Gearscape"
            aria-label="Copy current items to clipboard for Gearscape"
          >
            {gearscapeExportLabel}
          </button>
        ) : undefined}
        <span className="rsborder-tiny rsbackground rsbackground-hover">
          HA:&nbsp;<span>{totalHighAlch.toLocaleString()}</span>
          <span>gp</span>
        </span>
        <span className="rsborder-tiny rsbackground rsbackground-hover">
          GE:&nbsp;<span>{totalGEPrice.toLocaleString()}</span>
          <span>gp</span>
        </span>
      </div>
      <ItemPanelsScrollArea
        sortedItems={sortedItems}
        memberFilter={memberFilter}
        containerFilter={containerFilter}
        pinnedItems={pinnedItems}
        onTogglePin={togglePin}
      />
    </>
  );
};
