// resources/components/login-page/login-page.tsx
import {
  Fragment,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
  type ReactElement,
  type ReactNode,
} from "react";
import { Context as APIContext } from "../../context/api-context";
import { useNavigate, useLocation } from "react-router-dom";
import * as z from "zod/v4";
import { LoadingScreen } from "../loading-screen/loading-screen";

import "./login-page.css";

const NameSchema = z
  .string("Name is required.")
  .transform((name) => name.trim())
  .refine((name) => name.length > 0, {
    error: "Name is required.",
  });

const TokenSchema = z
  .string("Token is required.")
  .transform((name) => name.trim())
  .refine((name) => name.length > 0, {
    error: "Token is required.",
  });

export const LoginPage = (): ReactElement => {
  const { logInLive } = useContext(APIContext) ?? {};
  const [nameError, setNameError] = useState<string[]>();
  const [tokenError, setTokenError] = useState<string[]>();
  const [serverError, setServerError] = useState<string[]>();
  const [pendingSubmission, setPendingSubmission] = useState<boolean>(false);
  const navigate = useNavigate();
  const location = useLocation();
  const isAddingGroup = (location.state as { addGroup?: boolean } | null)?.addGroup === true;

  const formRef = useRef<HTMLFormElement>(null);
  useEffect(() => {
    const watchReset = (e: Event): void => {
      e.preventDefault();
    };
    const form = formRef.current;
    if (!form) return;

    form.addEventListener("reset", watchReset);

    return (): void => {
      form.removeEventListener("reset", watchReset);
    };
  }, []);

  useEffect(() => {
    if (!logInLive || isAddingGroup) return;

    logInLive()
      .then(() => {
        return navigate("/group/items", { replace: true });
      })
      .catch((reason) => {
        console.error("LoginPage: Error while redirecting:", reason);
      });
  }, [logInLive, navigate, isAddingGroup]);

  const tryLogin = useCallback(
    (formData: FormData): void => {
      const groupNameParsed = NameSchema.safeParse(formData.get("login-group-name")?.valueOf());
      const groupTokenParsed = TokenSchema.safeParse(formData.get("login-group-token")?.valueOf());

      setServerError(undefined);

      if (!groupNameParsed.success || !groupTokenParsed.success) {
        if (!groupNameParsed.success) {
          setNameError(z.flattenError(groupNameParsed.error).formErrors);
        }
        if (!groupTokenParsed.success) {
          setTokenError(z.flattenError(groupTokenParsed.error).formErrors);
        }
        return;
      }

      const credentials = { name: groupNameParsed.data, token: groupTokenParsed.data };

      if (!logInLive) {
        console.error("LoginPage: LogInLive was undefined, but form was still submitted.");
        return;
      }

      setPendingSubmission(true);
      setNameError(undefined);
      setTokenError(undefined);
      new Promise<void>((resolve) => setTimeout(resolve, 500))
        .then(() => {
          return logInLive(credentials).then(() => navigate("/group"));
        })
        .catch((reason) => {
          if (reason instanceof Error) {
            setServerError([reason.message]);
          }
          console.error("LoginPage: Error during form submission:", reason);
        })
        .finally(() => {
          setPendingSubmission(false);
        });
    },
    [navigate, logInLive],
  );

  const serverErrorsElement = ((): ReactNode => {
    if ((serverError?.length ?? 0) < 1) {
      return undefined;
    }

    return (
      <div className="validation-error">
        {serverError?.map((string, index) => (
          <Fragment key={string}>
            {index > 0 ? <br /> : undefined}
            {string}
          </Fragment>
        ))}
      </div>
    );
  })();

  const pendingOverlay = pendingSubmission ? (
    <div id="login-page-loading-overlay">
      <LoadingScreen />
    </div>
  ) : undefined;

  const pending = pendingSubmission || !logInLive;
  return (
    <div id="login-page-container">
      <form ref={formRef} id="login-page-window" className="rsborder rsbackground" action={tryLogin}>
        <div className="login-page-step">
          <label htmlFor="login-group-name">Group name</label>
          <br />
          <input
            aria-required
            id="login-group-name"
            className={nameError ? "invalid" : "valid"}
            name="login-group-name"
            placeholder="Group name"
            maxLength={16}
          />
          <div className="validation-error">
            {nameError?.map((error, index) => (
              <Fragment key={error}>
                {index > 0 ? <br /> : undefined}
                {error}
              </Fragment>
            ))}
          </div>
        </div>
        <div className="login-page-step">
          <label htmlFor="login-group-token">Group token</label>
          <br />
          <input
            aria-required
            id="login-group-token"
            className={tokenError ? "invalid" : "valid"}
            name="login-group-token"
            placeholder="Group token"
            maxLength={60}
            type="password"
          />
          <div className="validation-error">
            {tokenError?.map((error, index) => (
              <Fragment key={error}>
                {index > 0 ? <br /> : undefined}
                {error}
              </Fragment>
            ))}
          </div>
        </div>
        <button disabled={pending} id="login-page-submit" className="men-button" type="submit">
          Login
        </button>
        {serverErrorsElement}
        {pendingOverlay}
      </form>
    </div>
  );
};

// resources/components/login-page/LoginPage.vue
<script setup>
  import { computed, ref } from "vue";
  import { useRoute, useRouter } from "vue-router";
  import * as z from "zod/v4";
  import { useApiStore } from "../../stores/api";
  import LoadingScreen from "../loading-screen/LoadingScreen.vue";
  import "./login-page.css";

  const requiredValueSchema = z.string().trim().min(1, "This field is required.");

  const apiStore = useApiStore();
  const route = useRoute();
  const router = useRouter();

  const nameErrors = ref();
  const tokenErrors = ref();
  const serverErrors = ref();
  const pendingSubmission = ref(false);

  const isAddingGroup = computed(function addingGroup() {
    return route.query.addGroup === "true";
  });

  async function tryLogin(event) {
    const formData = new FormData(event.currentTarget);
    const groupName = requiredValueSchema.safeParse(formData.get("login-group-name"));
    const groupToken = requiredValueSchema.safeParse(formData.get("login-group-token"));

    serverErrors.value = undefined;
    nameErrors.value = groupName.success ? undefined : ["Name is required."];
    tokenErrors.value = groupToken.success ? undefined : ["Token is required."];

    if (!groupName.success || !groupToken.success) {
      return;
    }

    pendingSubmission.value = true;

    try {
      await new Promise(function waitForLoadingState(resolve) {
        setTimeout(resolve, 500);
      });
      await apiStore.logInLive({ name: groupName.data, token: groupToken.data });
      await router.push("/group");
    } catch (reason) {
      if (reason instanceof Error) {
        serverErrors.value = [reason.message];
      }

      console.error("LoginPage: Error during form submission:", reason);
    } finally {
      pendingSubmission.value = false;
    }
  }
</script>

<template>
  <div id="login-page-container">
    <form id="login-page-window" class="rsborder rsbackground" @submit.prevent="tryLogin">
      <div class="login-page-step">
        <label for="login-group-name">Group name</label>
        <br />
        <input
          aria-required="true"
          id="login-group-name"
          :class="nameErrors ? 'invalid' : 'valid'"
          name="login-group-name"
          placeholder="Group name"
          maxlength="16"
        />
        <div class="validation-error">
          <template v-for="(error, index) in nameErrors" :key="error">
            <br v-if="index > 0" />
            {{ error }}
          </template>
        </div>
      </div>

      <div class="login-page-step">
        <label for="login-group-token">Group token</label>
        <br />
        <input
          aria-required="true"
          id="login-group-token"
          :class="tokenErrors ? 'invalid' : 'valid'"
          name="login-group-token"
          placeholder="Group token"
          maxlength="60"
          type="password"
        />
        <div class="validation-error">
          <template v-for="(error, index) in tokenErrors" :key="error">
            <br v-if="index > 0" />
            {{ error }}
          </template>
        </div>
      </div>

      <button :disabled="pendingSubmission" id="login-page-submit" class="men-button" type="submit">Login</button>

      <div v-if="serverErrors?.length" class="validation-error">
        <template v-for="(error, index) in serverErrors" :key="error">
          <br v-if="index > 0" />
          {{ error }}
        </template>
      </div>

      <div v-if="pendingSubmission" id="login-page-loading-overlay">
        <LoadingScreen />
      </div>
    </form>
  </div>
</template>
